//! Wii disc layout reader (D116): parse the disc header, the partition
//! table and every partition's header into an EXACT coverage map of
//! the image, verify each partition body's hash tree against its own
//! plaintext, and walk the plaintext with the GameCube volume walker —
//! so the `wii-split/1` analyzer can decompose the image into
//! `assemble@1` pieces, one zero-input junk recipe, and per-partition
//! `xf-wii-crypt` routes.
//!
//! # The disc
//!
//! A Wii disc is a 0x400-byte header (game ID, disc number, the Wii
//! magic at 0x18, and at 0x60/0x61 the "no hashes" / "no encryption"
//! flags a retail master never sets), a partition table at 0x40000
//! (four groups of `(count, entries offset >> 2)`, each entry
//! `(partition offset >> 2, kind)`), region.bin at 0x4E000, and the
//! partitions themselves — each a 0x2C0-byte header (the ticket, then
//! the TMD / certificate chain / H3 table / data offsets and sizes,
//! all `>> 2`), the structures it points at, and the encrypted BODY:
//! `data_size` bytes of 32 KiB sectors (docs in `datboi-xf-wii-crypt`).
//! Every byte the tables do not name is mastering junk (the GameCube
//! generator seeded from the disc's ID and disc number, over the DISC's
//! address space), a zero pad, or residue.
//!
//! # A partition
//!
//! The body decrypts to a plaintext of `sectors × 0x7C00` bytes that
//! is a GameCube-shaped volume: boot block (Wii magic, offsets `>> 2`),
//! bi2, apploader, DOL, FST, files — and junk in every unused byte,
//! generated by the generator seeded from the PARTITION's own boot
//! block ID and disc number over the PLAINTEXT's address space (measured
//! on a real disc: the update and channel partitions, whose IDs differ
//! from the disc's, match their own ID and leave ~60 bytes of residue,
//! and match nothing under the disc's — `nod` seeds every partition
//! from the disc header, which only coincides on the data partition).
//! So a partition's plaintext walks with [`crate::gcm::parse_volume`]
//! verbatim; a partition whose seed is the disc's shares the disc's one
//! junk stream (the same generator over a prefix of the same address
//! space), any other claims its own.
//!
//! # Verification before any claim
//!
//! The body's rebuild is `encrypt(plaintext, common key)`. It is claimed
//! only after this module has decrypted every sector, recomputed the
//! H0/H1/H2 tree from the plaintext and compared it to the disc's own
//! hash blocks BYTE FOR BYTE — padding included, because that is what
//! re-encryption reproduces. A partition that fails stays an opaque
//! piece of the disc (the decomposition of the disc around it is still
//! exact); a wrong guess costs storage, never a wrong claim, and D4
//! replay is the proof either way. Structural anomalies are settled
//! conclusions ([`Refusal`]), never environmental errors (D81).

use std::collections::HashMap;
use std::io::{self, Read, Seek, SeekFrom};

use datboi_core::assemble::LITERAL_CAP;
use datboi_core::hash::Blake3;
use datboi_xf_wii_crypt::{
    DATA_LEN, GROUP_SECTORS, GroupHashes, Key, SECTOR_LEN, decrypt_data, decrypt_sector,
    hash_block_matches, title_key,
};

use crate::gcm::{self, Classifier, GcmError, Junk, VolumeOpts, WII_MAGIC, junk_stream};
use crate::nds::{Piece, Region, read_at};

/// Length of the disc header the walk keeps as a literal.
pub const HEADER_LEN: u64 = 0x400;
/// The partition table: four `(count, entries offset)` groups.
pub const PARTITION_TABLE: u64 = 0x40000;
const PARTITION_GROUPS: u64 = 4;
/// region.bin.
pub const REGION_OFFSET: u64 = 0x4E000;
pub const REGION_LEN: u64 = 0x20;
/// A partition header: the ticket, then seven `u32`s.
pub const PARTITION_HEADER_LEN: u64 = 0x2C0;
pub const TICKET_LEN: u64 = 0x2A4;
/// The H3 table's fixed size.
pub const H3_LEN: u64 = 0x18000;
/// Partition kinds as the table names them.
pub const KIND_DATA: u32 = 0;
pub const KIND_UPDATE: u32 = 1;
pub const KIND_CHANNEL: u32 = 2;
/// A table claiming more partitions than this is a lie.
const MAX_PARTITIONS: u64 = 64;
/// A TMD or certificate chain above this is a lie.
const MAX_META_LEN: u64 = 1 << 20;
const SECTOR: u64 = SECTOR_LEN as u64;
const GROUP_LEN: u64 = SECTOR * GROUP_SECTORS as u64;

/// Structural refusals — deterministic conclusions about the bytes.
#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum Refusal {
    #[error("not a wii disc (no magic at 0x18)")]
    NotWii,
    #[error("a gamecube disc (magic at 0x1c) — not a wii image")]
    GameCube,
    #[error("truncated: {0}")]
    Truncated(&'static str),
    #[error("header: {0}")]
    Header(String),
    #[error("partition {0}: {1}")]
    Partition(usize, String),
    #[error("declared ranges overlap: {0} and {1}")]
    Overlap(String, String),
    #[error(
        "partition {0}: ticket issuer {1:?} / common key index {2} is not a key this build knows"
    )]
    UnknownKey(usize, String, u8),
    #[error(
        "the header declares no partition hashes — a decrypted or scrubbed image, not a master"
    )]
    NoHashes,
    #[error("the header declares no partition encryption — a decrypted image, not a master")]
    NoEncryption,
}

#[derive(Debug, thiserror::Error)]
pub enum WiiError {
    #[error(transparent)]
    Io(#[from] io::Error),
    #[error(transparent)]
    Refused(#[from] Refusal),
}

impl From<GcmError> for WiiError {
    fn from(e: GcmError) -> Self {
        match e {
            GcmError::Io(e) => Self::Io(e),
            GcmError::Refused(r) => Self::Refused(Refusal::Header(r.to_string())),
        }
    }
}

/// A common key this build recognizes — by the blake3 of its 16 bytes
/// (D12/D116: keys are content-addressed blobs the user holds; the
/// software knows their NAMES, never their bytes). The ticket's issuer
/// string and common-key index select which one a partition needs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct KnownKey {
    pub issuer: &'static str,
    pub index: u8,
    pub hash: Blake3,
}

/// The retail (ppki) and debug (dpki) issuers.
pub const ISSUER_RETAIL: &str = "Root-CA00000001-XS00000003";
pub const ISSUER_DEBUG: &str = "Root-CA00000002-XS00000006";

/// The six console common keys, by hash: retail / Korean / vWii, and
/// their debug counterparts.
#[must_use]
pub fn known_keys() -> Vec<KnownKey> {
    const TABLE: [(&str, u8, &str); 6] = [
        (
            ISSUER_RETAIL,
            0,
            "53f29fea4d55090f83630b9e20578116a7105ba6d9e92dc977f0b48dfd477328",
        ),
        (
            ISSUER_RETAIL,
            1,
            "3bd9823c237cdac3b1ec8f12146d149969f6479160a9de3f3aae68a31ccd9e60",
        ),
        (
            ISSUER_RETAIL,
            2,
            "199b2a1966d21eb0e220cc04afa42be9f5c7f5160913ecd87beb90e00b910f6f",
        ),
        (
            ISSUER_DEBUG,
            0,
            "563b29355b63af5871521e19d8448f5c377875c04c4234ee2eef2a9e51ce8f97",
        ),
        (
            ISSUER_DEBUG,
            1,
            "68dcf0859bb3988b15d24b2912f17275e1bb22b6b0bf5e946a52e80c552fc7ff",
        ),
        (
            ISSUER_DEBUG,
            2,
            "14adb027db46e22cdde27226ed78ef4b6810a2581157c9024dac0c12cdd840aa",
        ),
    ];
    TABLE
        .iter()
        .map(|(issuer, index, hex)| KnownKey {
            issuer,
            index: *index,
            hash: hex.parse().expect("well-formed constant"),
        })
        .collect()
}

/// The disc header's facts the walk needs.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DiscHeader {
    pub game_id: [u8; 6],
    pub disc: u8,
}

/// A ticket's key-selecting fields (the rest rides as a piece).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Ticket {
    pub issuer: String,
    pub wrapped_title_key: [u8; 16],
    pub title_id: [u8; 8],
    pub common_key_index: u8,
}

/// One partition as the table and its header describe it, offsets
/// absolute in the image.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PartitionHeader {
    /// Position in table order.
    pub index: usize,
    pub kind: u32,
    pub offset: u64,
    pub ticket: Ticket,
    pub tmd_offset: u64,
    pub tmd_len: u64,
    pub cert_offset: u64,
    pub cert_len: u64,
    pub h3_offset: u64,
    pub data_offset: u64,
    pub data_len: u64,
}

impl PartitionHeader {
    /// Sectors in the body.
    #[must_use]
    pub fn sectors(&self) -> u64 {
        self.data_len / SECTOR
    }

    /// Plaintext length of the body.
    #[must_use]
    pub fn plain_len(&self) -> u64 {
        self.sectors() * DATA_LEN as u64
    }

    /// Piece name prefix: `part<index>-<kind>` — the kind by name, or a
    /// channel partition's four-character code (a real disc's channel
    /// partitions carry their title ID as the kind).
    #[must_use]
    pub fn prefix(&self) -> String {
        let kind = match self.kind {
            KIND_DATA => "data".to_owned(),
            KIND_UPDATE => "update".to_owned(),
            KIND_CHANNEL => "channel".to_owned(),
            k => {
                let b = k.to_be_bytes();
                if b.iter().all(|c| c.is_ascii_alphanumeric()) {
                    String::from_utf8_lossy(&b).into_owned()
                } else {
                    format!("kind{k}")
                }
            }
        };
        format!("part{}-{kind}", self.index)
    }
}

fn be32(buf: &[u8], at: usize) -> u64 {
    u64::from(u32::from_be_bytes([
        buf[at],
        buf[at + 1],
        buf[at + 2],
        buf[at + 3],
    ]))
}

/// True if `head` (≥ 0x20 bytes at offset 0) carries the Wii magic.
#[must_use]
pub fn looks_like_wii(head: &[u8]) -> bool {
    head.len() >= 0x1C && head[0x18..0x1C] == WII_MAGIC
}

/// Read and check the disc header.
///
/// # Errors
/// [`WiiError::Refused`] for anything but an encrypted, hashed Wii
/// master; `Io` is environmental.
pub fn read_disc_header<R: Read + Seek>(img: &mut R) -> Result<DiscHeader, WiiError> {
    let total_len = img.seek(SeekFrom::End(0))?;
    if total_len < REGION_OFFSET + REGION_LEN {
        return Err(Refusal::NotWii.into());
    }
    let head = read_at(img, 0, usize::try_from(HEADER_LEN).expect("small"))?;
    if gcm::looks_like_gcm(&head) {
        return Err(Refusal::GameCube.into());
    }
    if !looks_like_wii(&head) {
        return Err(Refusal::NotWii.into());
    }
    if head[0x60] != 0 {
        return Err(Refusal::NoHashes.into());
    }
    if head[0x61] != 0 {
        return Err(Refusal::NoEncryption.into());
    }
    Ok(DiscHeader {
        game_id: head[..6].try_into().expect("6 bytes"),
        disc: head[6],
    })
}

/// Read the partition table and every partition's header. Cheap — a
/// few small reads — so the analyzer can resolve keys before any
/// heavy work.
///
/// # Errors
/// Structural lies are refusals; `Io` is environmental.
pub fn read_partitions<R: Read + Seek>(img: &mut R) -> Result<Vec<PartitionHeader>, WiiError> {
    let total_len = img.seek(SeekFrom::End(0))?;
    let groups = read_at(
        img,
        PARTITION_TABLE,
        usize::try_from(PARTITION_GROUPS * 8).expect("small"),
    )?;
    let mut entries: Vec<(u64, u32)> = Vec::new();
    for g in 0..PARTITION_GROUPS {
        let at = usize::try_from(g * 8).expect("small");
        let count = be32(&groups, at);
        let entries_off = be32(&groups, at + 4) << 2;
        if count == 0 {
            continue;
        }
        if count > MAX_PARTITIONS || entries.len() as u64 + count > MAX_PARTITIONS {
            return Err(Refusal::Header(format!(
                "partition group {g} declares {count} partitions"
            ))
            .into());
        }
        if entries_off + count * 8 > total_len {
            return Err(Refusal::Truncated("partition entries past the image").into());
        }
        let block = read_at(
            img,
            entries_off,
            usize::try_from(count * 8).expect("bounded"),
        )?;
        for i in 0..usize::try_from(count).expect("bounded") {
            let offset = be32(&block, i * 8) << 2;
            let kind = u32::try_from(be32(&block, i * 8 + 4)).expect("u32");
            entries.push((offset, kind));
        }
    }
    if entries.is_empty() {
        return Err(Refusal::Header("no partitions".into()).into());
    }
    let mut parts = Vec::with_capacity(entries.len());
    for (index, (offset, kind)) in entries.into_iter().enumerate() {
        if !offset.is_multiple_of(SECTOR) {
            return Err(Refusal::Partition(index, "offset is not sector aligned".into()).into());
        }
        if offset + PARTITION_HEADER_LEN > total_len {
            return Err(Refusal::Truncated("partition header past the image").into());
        }
        let h = read_at(
            img,
            offset,
            usize::try_from(PARTITION_HEADER_LEN).expect("small"),
        )?;
        let issuer_bytes = &h[0x140..0x180];
        let issuer = issuer_bytes
            .split(|&b| b == 0)
            .next()
            .map(|s| String::from_utf8_lossy(s).into_owned())
            .unwrap_or_default();
        let ticket = Ticket {
            issuer,
            wrapped_title_key: h[0x1BF..0x1CF].try_into().expect("16 bytes"),
            title_id: h[0x1DC..0x1E4].try_into().expect("8 bytes"),
            common_key_index: h[0x1F1],
        };
        let tmd_len = be32(&h, 0x2A4);
        let tmd_offset = offset + (be32(&h, 0x2A8) << 2);
        let cert_len = be32(&h, 0x2AC);
        let cert_offset = offset + (be32(&h, 0x2B0) << 2);
        let h3_offset = offset + (be32(&h, 0x2B4) << 2);
        let data_offset = offset + (be32(&h, 0x2B8) << 2);
        let data_len = be32(&h, 0x2BC) << 2;
        if tmd_len > MAX_META_LEN || cert_len > MAX_META_LEN {
            return Err(Refusal::Partition(
                index,
                "implausible tmd or certificate chain size".into(),
            )
            .into());
        }
        if !data_offset.is_multiple_of(SECTOR) || !data_len.is_multiple_of(SECTOR) {
            return Err(Refusal::Partition(index, "body is not sector aligned".into()).into());
        }
        if data_len == 0 {
            return Err(Refusal::Partition(index, "empty body".into()).into());
        }
        for (what, end) in [
            ("tmd", tmd_offset + tmd_len),
            ("certificate chain", cert_offset + cert_len),
            ("h3 table", h3_offset + H3_LEN),
            ("body", data_offset + data_len),
        ] {
            if end > total_len {
                return Err(Refusal::Partition(index, format!("{what} past the image")).into());
            }
        }
        parts.push(PartitionHeader {
            index,
            kind,
            offset,
            ticket,
            tmd_offset,
            tmd_len,
            cert_offset,
            cert_len,
            h3_offset,
            data_offset,
            data_len,
        });
    }
    Ok(parts)
}

/// Which known key a ticket selects.
#[must_use]
pub fn key_for<'k>(keys: &'k [KnownKey], ticket: &Ticket) -> Option<&'k KnownKey> {
    keys.iter()
        .find(|k| k.issuer == ticket.issuer && k.index == ticket.common_key_index)
}

/// What the verification pass concluded about one body.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BodyVerdict {
    /// blake3 of the encrypted body — the piece's identity.
    pub body_hash: Blake3,
    /// blake3 of the plaintext — the decrypt route's output identity.
    pub plain_hash: Blake3,
    /// Every hash block equals what its group's plaintext yields.
    pub verified: bool,
    /// The first sector whose hash block disagreed, when not verified.
    pub first_bad_sector: Option<u64>,
}

/// One sequential pass over a body: decrypt every sector, recompute
/// each group's tree, compare the hash blocks, and hash both the
/// ciphertext and the plaintext on the way.
///
/// # Errors
/// I/O only — a disagreeing hash block is a verdict, not an error.
pub fn verify_body<R: Read + Seek>(
    img: &mut R,
    part: &PartitionHeader,
    key: &Key,
) -> io::Result<BodyVerdict> {
    let title = title_key(key, &part.ticket.wrapped_title_key, &part.ticket.title_id);
    let sectors = part.sectors();
    let mut body_hasher = blake3::Hasher::new();
    let mut plain_hasher = blake3::Hasher::new();
    let mut verified = true;
    let mut first_bad = None;
    let mut enc = vec![0u8; usize::try_from(GROUP_LEN).expect("2 MiB")];
    let mut plain = vec![0u8; DATA_LEN * GROUP_SECTORS];
    let mut sector_plain = [0u8; SECTOR_LEN];
    img.seek(SeekFrom::Start(part.data_offset))?;
    let mut done = 0u64;
    while done < sectors {
        let n = usize::try_from((sectors - done).min(GROUP_SECTORS as u64)).expect("<= 64");
        let take = n * SECTOR_LEN;
        img.read_exact(&mut enc[..take])?;
        body_hasher.update(&enc[..take]);
        for s in 0..n {
            let e: &[u8; SECTOR_LEN] = enc[s * SECTOR_LEN..(s + 1) * SECTOR_LEN]
                .try_into()
                .expect("exact");
            decrypt_sector(&title, e, &mut sector_plain);
            plain[s * DATA_LEN..(s + 1) * DATA_LEN]
                .copy_from_slice(&sector_plain[SECTOR_LEN - DATA_LEN..]);
            // Keep the decrypted hash block for the comparison below.
            enc[s * SECTOR_LEN..s * SECTOR_LEN + (SECTOR_LEN - DATA_LEN)]
                .copy_from_slice(&sector_plain[..SECTOR_LEN - DATA_LEN]);
        }
        plain_hasher.update(&plain[..n * DATA_LEN]);
        if verified {
            let hashes = GroupHashes::compute(&plain[..n * DATA_LEN]);
            for s in 0..n {
                sector_plain[..SECTOR_LEN - DATA_LEN].copy_from_slice(
                    &enc[s * SECTOR_LEN..s * SECTOR_LEN + (SECTOR_LEN - DATA_LEN)],
                );
                if !hash_block_matches(&sector_plain, &hashes, s) {
                    verified = false;
                    first_bad = Some(done + s as u64);
                    break;
                }
            }
        }
        done += n as u64;
    }
    Ok(BodyVerdict {
        body_hash: Blake3(*body_hasher.finalize().as_bytes()),
        plain_hash: Blake3(*plain_hasher.finalize().as_bytes()),
        verified,
        first_bad_sector: first_bad,
    })
}

/// `Read + Seek` over a partition's plaintext, decrypting sectors on
/// demand out of the image with a one-sector cache — the `rom` the
/// volume walker and the piece hasher read through.
pub struct PlainReader<'r, R> {
    img: &'r mut R,
    base: u64,
    sectors: u64,
    key: Key,
    pos: u64,
    cached: u64,
    enc: Box<[u8; SECTOR_LEN]>,
    data: Box<[u8; DATA_LEN]>,
}

impl<'r, R: Read + Seek> PlainReader<'r, R> {
    /// Over `part`'s body under the common key `key`.
    pub fn new(img: &'r mut R, part: &PartitionHeader, key: &Key) -> Self {
        Self {
            img,
            base: part.data_offset,
            sectors: part.sectors(),
            key: title_key(key, &part.ticket.wrapped_title_key, &part.ticket.title_id),
            pos: 0,
            cached: u64::MAX,
            enc: Box::new([0u8; SECTOR_LEN]),
            data: Box::new([0u8; DATA_LEN]),
        }
    }

    /// Plaintext length.
    #[must_use]
    pub fn len(&self) -> u64 {
        self.sectors * DATA_LEN as u64
    }

    /// True when the body has no sectors.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.sectors == 0
    }

    fn load(&mut self, sector: u64) -> io::Result<()> {
        if self.cached == sector {
            return Ok(());
        }
        self.img
            .seek(SeekFrom::Start(self.base + sector * SECTOR))?;
        self.img.read_exact(&mut self.enc[..])?;
        decrypt_data(&self.key, &self.enc, &mut self.data[..]);
        self.cached = sector;
        Ok(())
    }
}

impl<R: Read + Seek> Read for PlainReader<'_, R> {
    fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        let len = self.len();
        if self.pos >= len || buf.is_empty() {
            return Ok(0);
        }
        let sector = self.pos / DATA_LEN as u64;
        let within = usize::try_from(self.pos % DATA_LEN as u64).expect("< sector");
        self.load(sector)?;
        let n = (DATA_LEN - within)
            .min(buf.len())
            .min(usize::try_from(len - self.pos).unwrap_or(usize::MAX));
        buf[..n].copy_from_slice(&self.data[within..within + n]);
        self.pos += n as u64;
        Ok(n)
    }
}

impl<R: Read + Seek> Seek for PlainReader<'_, R> {
    fn seek(&mut self, pos: SeekFrom) -> io::Result<u64> {
        let len = self.len();
        let next = match pos {
            SeekFrom::Start(p) => Some(p),
            SeekFrom::End(d) => len.checked_add_signed(d),
            SeekFrom::Current(d) => self.pos.checked_add_signed(d),
        };
        let next = next.ok_or_else(|| io::Error::other("seek before start"))?;
        self.pos = next;
        Ok(next)
    }
}

/// One partition's part of the layout.
#[derive(Debug)]
pub struct PartitionLayout {
    pub header: PartitionHeader,
    pub verdict: BodyVerdict,
    /// The plaintext's coverage map — `None` when the body did not
    /// verify (it stays an opaque piece of the disc) or its plaintext
    /// is not a volume the walker accepts.
    pub plain: Option<gcm::Layout>,
    /// Why `plain` is `None`, for the verdict detail.
    pub opaque_reason: Option<String>,
    /// Index of the body piece in [`Layout::pieces`].
    pub body_piece: usize,
    /// The partition's junk seed: its boot block's ID and disc number.
    pub seed: ([u8; 4], u8),
    /// The partition's OWN junk stream — `Some` only when its seed is
    /// not the disc's and junk matched; otherwise its junk ranges are
    /// ranges of [`Layout::junk`].
    pub junk: Option<Junk>,
}

#[derive(Debug)]
pub struct Layout {
    pub total_len: u64,
    pub header: DiscHeader,
    /// The disc's own coverage map: header structures, per-partition
    /// tickets / TMDs / certificate chains / H3 tables as pieces,
    /// bodies as pieces (pre-hashed by the verification pass), gaps
    /// classified. [`Region::Extern`] regions reference the junk stream
    /// (extern input 0) at disc offsets.
    pub pieces: Vec<Piece>,
    pub regions: Vec<Region>,
    /// Hashes already computed for pieces (the bodies), by piece index.
    pub prehashed: HashMap<usize, Blake3>,
    pub partitions: Vec<PartitionLayout>,
    /// The disc's junk stream over its whole address space: `Some` when
    /// junk matched on the disc itself or inside a partition seeded like
    /// the disc (the data partition).
    pub junk: Option<Junk>,
    /// Disc-level (outside the bodies) classification.
    pub junk_bytes: u64,
    pub fill_bytes: u64,
    pub residual_bytes: u64,
}

impl Layout {
    /// Junk bytes matched across the disc and every walked partition.
    #[must_use]
    pub fn total_junk_bytes(&self) -> u64 {
        self.junk_bytes
            + self
                .partitions
                .iter()
                .filter_map(|p| p.plain.as_ref())
                .map(|l| l.junk_bytes)
                .sum::<u64>()
    }
}

#[derive(Debug, Clone)]
struct Entry {
    name: String,
    start: u64,
    len: u64,
    literal: bool,
}

/// Walk the image. `keys` pairs each partition (by index into the
/// [`read_partitions`] list) with the 16-byte common key its ticket
/// selects; every partition must have one.
///
/// # Errors
/// [`WiiError::Refused`] is a settled conclusion; `Io` is environmental.
pub fn parse_layout<R: Read + Seek>(
    img: &mut R,
    max_pieces: usize,
    header: DiscHeader,
    parts: &[PartitionHeader],
    keys: &[Key],
) -> Result<Layout, WiiError> {
    assert_eq!(parts.len(), keys.len(), "one key per partition");
    let total_len = img.seek(SeekFrom::End(0))?;
    let id4: [u8; 4] = header.game_id[..4].try_into().expect("4 bytes");

    // Declared ranges: the header structures and the partition table
    // (literal-sized), then per partition its structures and body.
    let mut entries: Vec<Entry> = vec![
        Entry {
            name: "sys/header.bin".into(),
            start: 0,
            len: HEADER_LEN,
            literal: true,
        },
        Entry {
            name: "sys/region.bin".into(),
            start: REGION_OFFSET,
            len: REGION_LEN,
            literal: true,
        },
    ];
    {
        // The table spans the groups block and every entries block.
        let groups = read_at(
            img,
            PARTITION_TABLE,
            usize::try_from(PARTITION_GROUPS * 8).expect("small"),
        )?;
        let mut end = PARTITION_TABLE + PARTITION_GROUPS * 8;
        for g in 0..PARTITION_GROUPS {
            let at = usize::try_from(g * 8).expect("small");
            let count = be32(&groups, at);
            if count > 0 {
                end = end.max((be32(&groups, at + 4) << 2) + count * 8);
            }
        }
        let len = end - PARTITION_TABLE;
        entries.push(Entry {
            name: "sys/partitions.bin".into(),
            start: PARTITION_TABLE,
            len,
            literal: len <= LITERAL_CAP as u64,
        });
    }
    let mut partitions: Vec<PartitionLayout> = Vec::with_capacity(parts.len());
    let mut body_names: Vec<String> = Vec::with_capacity(parts.len());
    for (part, key) in parts.iter().zip(keys) {
        let prefix = part.prefix();
        entries.push(Entry {
            name: format!("{prefix}/ticket.bin"),
            start: part.offset,
            len: TICKET_LEN,
            literal: false,
        });
        entries.push(Entry {
            name: format!("{prefix}/header-tail"),
            start: part.offset + TICKET_LEN,
            len: PARTITION_HEADER_LEN - TICKET_LEN,
            literal: true,
        });
        if part.tmd_len > 0 {
            entries.push(Entry {
                name: format!("{prefix}/tmd.bin"),
                start: part.tmd_offset,
                len: part.tmd_len,
                literal: false,
            });
        }
        if part.cert_len > 0 {
            entries.push(Entry {
                name: format!("{prefix}/cert.bin"),
                start: part.cert_offset,
                len: part.cert_len,
                literal: false,
            });
        }
        entries.push(Entry {
            name: format!("{prefix}/h3.bin"),
            start: part.h3_offset,
            len: H3_LEN,
            literal: false,
        });
        let body_name = format!("{prefix}/body.bin");
        entries.push(Entry {
            name: body_name.clone(),
            start: part.data_offset,
            len: part.data_len,
            literal: false,
        });
        body_names.push(body_name);

        // The body: verified, then walked as a volume when it verified,
        // its junk seeded from its OWN boot block.
        let verdict = verify_body(img, part, key)?;
        let mut seed = (id4, header.disc);
        let (plain, opaque_reason) = if verdict.verified {
            let mut reader = PlainReader::new(img, part, key);
            let boot = read_at(&mut reader, 0, 8)?;
            seed = (boot[..4].try_into().expect("4 bytes"), boot[6]);
            match gcm::parse_volume(
                &mut reader,
                max_pieces,
                VolumeOpts {
                    junk_id: seed.0,
                    junk_disc: seed.1,
                    wii: true,
                    hash_junk: false,
                },
            ) {
                Ok(layout) => (Some(layout), None),
                Err(GcmError::Refused(r)) => {
                    (None, Some(format!("plaintext is not a volume: {r}")))
                }
                Err(GcmError::Io(e)) => return Err(e.into()),
            }
        } else {
            (
                None,
                Some(format!(
                    "hash block of sector {} does not match its plaintext",
                    verdict.first_bad_sector.unwrap_or(0)
                )),
            )
        };
        let own_seed = seed != (id4, header.disc);
        let junk = match &plain {
            Some(l) if own_seed && l.junk_bytes > 0 => {
                Some(junk_stream(seed.0, seed.1, l.total_len))
            }
            _ => None,
        };
        partitions.push(PartitionLayout {
            header: part.clone(),
            verdict,
            plain,
            opaque_reason,
            body_piece: usize::MAX,
            seed,
            junk,
        });
    }

    entries.sort_by_key(|e| (e.start, e.len));
    entries.dedup_by(|b, a| a.start == b.start && a.len == b.len);
    for pair in entries.windows(2) {
        if pair[1].start < pair[0].start + pair[0].len {
            return Err(Refusal::Overlap(pair[0].name.clone(), pair[1].name.clone()).into());
        }
    }
    if let Some(last) = entries.last()
        && last.start + last.len > total_len
    {
        return Err(Refusal::Truncated("declared range past the image").into());
    }

    // Coverage: gaps classified against the disc's junk stream at disc
    // offsets, declared ranges as literals or pieces.
    let mut cls = Classifier::new(img, id4, header.disc);
    let mut pieces: Vec<Piece> = Vec::new();
    let mut regions: Vec<Region> = Vec::new();
    let mut prehashed: HashMap<usize, Blake3> = HashMap::new();
    let mut cursor = 0u64;
    for entry in entries {
        cls.classify(cursor, entry.start - cursor, &mut regions, &mut pieces)?;
        if entry.literal {
            regions.push(Region::Literal {
                start: entry.start,
                len: entry.len,
            });
        } else {
            let ix = pieces.len();
            if let Some(k) = body_names.iter().position(|n| *n == entry.name) {
                prehashed.insert(ix, partitions[k].verdict.body_hash);
                partitions[k].body_piece = ix;
            }
            regions.push(Region::Piece(ix));
            pieces.push(Piece {
                name: entry.name,
                start: entry.start,
                len: entry.len,
            });
        }
        cursor = entry.start + entry.len;
    }
    cls.classify(cursor, total_len - cursor, &mut regions, &mut pieces)?;
    let junk_bytes = cls.junk_bytes;
    let fill_bytes = cls.fill_bytes;
    let residual_bytes = cls.residual_bytes;

    // The disc's junk stream (D116): its address space is the image's,
    // and a partition seeded like the disc has a plaintext shorter than
    // the image, so its junk ranges fall inside the same stream.
    let any_junk = junk_bytes > 0
        || partitions
            .iter()
            .filter(|p| p.junk.is_none())
            .filter_map(|p| p.plain.as_ref())
            .any(|l| l.junk_bytes > 0);
    let junk = any_junk.then(|| junk_stream(id4, header.disc, total_len));

    Ok(Layout {
        total_len,
        header,
        pieces,
        regions,
        prehashed,
        partitions,
        junk,
        junk_bytes,
        fill_bytes,
        residual_bytes,
    })
}

/// Synthetic disc builder for the gates: a small Wii image (the
/// analyzer assumes nothing about size) with one encrypted data
/// partition whose plaintext is the GameCube synthetic volume, real
/// hash trees, junk from the generator on the disc and inside the
/// partition, a zero pad, and a test common key.
#[doc(hidden)]
pub mod synth {
    use super::{
        H3_LEN, HEADER_LEN, ISSUER_RETAIL, PARTITION_HEADER_LEN, PARTITION_TABLE, REGION_OFFSET,
        SECTOR, WII_MAGIC,
    };
    use crate::gcm::synth::{self as gc_synth, Pad};
    use datboi_xf_gc_junk::{Lfg, fill_at};
    use datboi_xf_wii_crypt::{
        DATA_LEN, GROUP_SECTORS, GroupHashes, Key, SECTOR_LEN, cbc_encrypt, encrypt_sector,
        title_key,
    };

    /// What the builder laid out, for assertions.
    pub struct Disc {
        pub bytes: Vec<u8>,
        pub id: [u8; 6],
        pub disc: u8,
        /// The test common key (never a real one).
        pub common_key: Key,
        pub wrapped_title_key: Key,
        pub title_id: [u8; 8],
        /// The partition's plaintext, as the walker will see it.
        pub plain: Vec<u8>,
        /// The encrypted body.
        pub body: Vec<u8>,
        /// Absolute offset of the partition (its header).
        pub partition_offset: u64,
        /// Absolute offset of the body.
        pub body_offset: u64,
        /// `(path, bytes)` in FST order, inside the partition.
        pub files: Vec<(String, Vec<u8>)>,
    }

    fn pattern(len: usize, salt: u32) -> Vec<u8> {
        (0..len)
            .map(|i| ((i as u32).wrapping_mul(2_654_435_761) ^ salt).to_le_bytes()[i % 4])
            .collect()
    }

    /// The test common key the builder encrypts under.
    #[must_use]
    pub fn test_common_key() -> Key {
        pattern(16, 0xC0DE).try_into().unwrap()
    }

    /// Build the disc. `files` are the partition's `(path, bytes)`;
    /// `pad` says whether unused space (disc-level and inside the
    /// partition) is junk or zeros.
    #[must_use]
    pub fn disc(id: [u8; 6], disc: u8, files: &[(&str, Vec<u8>)], pad: Pad) -> Disc {
        let common_key = test_common_key();
        let title_id: [u8; 8] = [0, 1, 0, 0, id[0], id[1], id[2], id[3]];
        let plain_title_key: Key = pattern(16, 0x7E7E).try_into().unwrap();
        let wrapped_title_key = {
            let mut iv = [0u8; 16];
            iv[..8].copy_from_slice(&title_id);
            let mut w = plain_title_key;
            cbc_encrypt(&common_key, &iv, &mut w);
            w
        };
        assert_eq!(
            title_key(&common_key, &wrapped_title_key, &title_id),
            plain_title_key
        );

        // The plaintext: the GameCube synthetic volume in Wii form, padded
        // to whole data sectors with junk (or zeros) at its own offsets.
        let volume = gc_synth::volume(id, disc, files, pad, true);
        let mut plain = volume.bytes;
        let sectors = plain.len().div_ceil(DATA_LEN);
        let padded = sectors * DATA_LEN;
        let old = plain.len();
        plain.resize(padded, 0);
        if pad == Pad::Junk {
            let id4: [u8; 4] = id[..4].try_into().unwrap();
            fill_at(
                &mut Lfg::default(),
                id4,
                disc,
                old as u64,
                &mut plain[old..],
            );
        }

        // Encrypt group by group.
        let mut body = Vec::with_capacity(sectors * SECTOR_LEN);
        let mut h3 = vec![0u8; usize::try_from(H3_LEN).unwrap()];
        let mut sector = [0u8; SECTOR_LEN];
        for (g, group) in plain.chunks(DATA_LEN * GROUP_SECTORS).enumerate() {
            let hashes = GroupHashes::compute(group);
            h3[g * 20..(g + 1) * 20].copy_from_slice(&hashes.h3);
            for (s, data) in group.chunks(DATA_LEN).enumerate() {
                encrypt_sector(&plain_title_key, &hashes, s, data, &mut sector);
                body.extend_from_slice(&sector);
            }
        }

        // Disc geometry: header region, then the partition at 0x50000
        // (header 0x2C0, TMD, cert chain, H3 at 0x8000, body at 0x20000),
        // then a trailing gap, then the end.
        let partition_offset = 0x50000u64;
        let tmd = pattern(0x208, 0x7D);
        let cert = pattern(0xA00, 0xCE);
        let tmd_offset = partition_offset + PARTITION_HEADER_LEN;
        let cert_offset = (tmd_offset + tmd.len() as u64).div_ceil(0x40) * 0x40;
        let h3_offset = partition_offset + 0x8000;
        let body_offset = partition_offset + 0x20000;
        let body_end = body_offset + body.len() as u64;
        let total = (body_end + 3 * SECTOR + 0x1234).div_ceil(SECTOR) * SECTOR;
        let mut out = vec![0u8; usize::try_from(total).unwrap()];
        if pad == Pad::Junk {
            let id4: [u8; 4] = id[..4].try_into().unwrap();
            fill_at(&mut Lfg::default(), id4, disc, 0, &mut out);
        }
        // Disc header.
        out[..usize::try_from(HEADER_LEN).unwrap()].fill(0);
        out[..6].copy_from_slice(&id);
        out[6] = disc;
        out[0x18..0x1C].copy_from_slice(&WII_MAGIC);
        out[0x20..0x2B].copy_from_slice(b"DATBOI TEST");
        // Partition table: one group, one data partition.
        let table = usize::try_from(PARTITION_TABLE).unwrap();
        out[table..table + 0x20].fill(0);
        out[table..table + 4].copy_from_slice(&1u32.to_be_bytes());
        out[table + 4..table + 8].copy_from_slice(
            &u32::try_from((PARTITION_TABLE + 0x20) >> 2)
                .unwrap()
                .to_be_bytes(),
        );
        out[table + 0x20..table + 0x24]
            .copy_from_slice(&u32::try_from(partition_offset >> 2).unwrap().to_be_bytes());
        out[table + 0x24..table + 0x28].copy_from_slice(&0u32.to_be_bytes());
        // region.bin.
        let region = usize::try_from(REGION_OFFSET).unwrap();
        out[region..region + 0x20].fill(0);
        out[region + 3] = 1;
        // Partition header: ticket (issuer, wrapped key, title id, key
        // index) then the seven sizes/offsets.
        let p = usize::try_from(partition_offset).unwrap();
        out[p..p + usize::try_from(PARTITION_HEADER_LEN).unwrap()].fill(0);
        out[p..p + 4].copy_from_slice(&0x0001_0001u32.to_be_bytes());
        out[p + 4..p + 0x104].copy_from_slice(&pattern(0x100, 0x516));
        out[p + 0x140..p + 0x140 + ISSUER_RETAIL.len()].copy_from_slice(ISSUER_RETAIL.as_bytes());
        out[p + 0x1BF..p + 0x1CF].copy_from_slice(&wrapped_title_key);
        out[p + 0x1DC..p + 0x1E4].copy_from_slice(&title_id);
        out[p + 0x1F1] = 0;
        let put = |out: &mut [u8], at: usize, v: u64| {
            out[at..at + 4].copy_from_slice(&u32::try_from(v).unwrap().to_be_bytes());
        };
        put(&mut out, p + 0x2A4, tmd.len() as u64);
        put(&mut out, p + 0x2A8, (tmd_offset - partition_offset) >> 2);
        put(&mut out, p + 0x2AC, cert.len() as u64);
        put(&mut out, p + 0x2B0, (cert_offset - partition_offset) >> 2);
        put(&mut out, p + 0x2B4, (h3_offset - partition_offset) >> 2);
        put(&mut out, p + 0x2B8, (body_offset - partition_offset) >> 2);
        put(&mut out, p + 0x2BC, (body.len() as u64) >> 2);
        let at = usize::try_from(tmd_offset).unwrap();
        out[at..at + tmd.len()].copy_from_slice(&tmd);
        let at = usize::try_from(cert_offset).unwrap();
        out[at..at + cert.len()].copy_from_slice(&cert);
        // Between the cert chain and H3: zeros (a real master's).
        let at = usize::try_from(cert_offset).unwrap() + cert.len();
        out[at..usize::try_from(h3_offset).unwrap()].fill(0);
        let at = usize::try_from(h3_offset).unwrap();
        out[at..at + h3.len()].copy_from_slice(&h3);
        out[at + h3.len()..usize::try_from(body_offset).unwrap()].fill(0);
        let at = usize::try_from(body_offset).unwrap();
        out[at..at + body.len()].copy_from_slice(&body);
        // A zero pad in the trailing gap, junk (or zeros) after it.
        let at = usize::try_from(body_end).unwrap();
        out[at..at + usize::try_from(SECTOR).unwrap() + 0x100].fill(0);
        Disc {
            bytes: out,
            id,
            disc,
            common_key,
            wrapped_title_key,
            title_id,
            plain,
            body,
            partition_offset,
            body_offset,
            files: volume.files,
        }
    }
}
