//! The /v1 API contract (D69): one typed struct per operation shape.
//!
//! This is the ONLY crate where serde/utoipa derives are legal. The
//! house no-derive rule exists because CAS object encodings ARE
//! identities (D18) — a macro must never own load-bearing bytes; D69
//! scopes that ban to canonical/content-addressed encodings. The HTTP
//! API is not that: it is a versioned, negotiable surface, so it gets
//! real types, and three consumers hang off them — the daemon's
//! handlers (datboi-server), the CHECKED-IN OpenAPI 3.1 spec
//! (`openapi.json`, regenerated by
//! `cargo run -p datboi-api --bin datboi-gen-openapi`, pinned byte-for-byte
//! by a test in this crate), and the web UI's generated TS client.
//!
//! Contract scope is exactly `/v1`. The minted-image download
//! (`GET /v1/views/{name}/image`) is in scope as an octet-stream
//! operation; the non-/v1 surfaces — the `/view/*` and `/snap/*` byte
//! trees (HTML/JSON listings, Range serving), `/dav`, NFS, and the
//! embedded UI fallback — are serving surfaces, not API operations,
//! and deliberately stay out of the spec.
//!
//! Field-level fidelity rule: these structs describe what actually
//! goes over the wire TODAY. Always-present-but-nullable fields are
//! `Option<T>`; omitted-when-absent fields carry
//! `#[serde(skip_serializing_if = "Option::is_none")]`.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

mod paths;

// ---- the uniform error shape ----

/// Every /v1 error body: `{"error": "<message>"}`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ApiError {
    /// Human-readable failure description.
    pub error: String,
}

/// The `{"ok": true}` acknowledgement mutations answer with.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct OkResponse {
    pub ok: bool,
}

// ---- shared vocabulary enums (lowercase on the wire) ----

/// User roles (D30/D68): owners see everything, friends see grants.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    Owner,
    Friend,
}

/// How a caller's identity arrived (whoami reports it). `loopback` is
/// the D68 implicit owner — a local shell already owns the daemon's
/// files.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "lowercase")]
pub enum Via {
    Loopback,
    Session,
    Bearer,
}

/// The UI's 4-state per-entry vocabulary, derived from the D39 rollup
/// (web spec §7). `nodump` entries are excluded from completeness math
/// client-side.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "lowercase")]
pub enum EntryState {
    Verified,
    Claimed,
    Missing,
    Nodump,
}

/// Per-claim rollup state — the entry vocabulary plus the two
/// non-holding grades (`peer`, `probable`) that fold into `missing` at
/// entry granularity.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "lowercase")]
pub enum ClaimState {
    Verified,
    Claimed,
    Peer,
    Probable,
    Missing,
    Nodump,
}

/// Blob residency (D21): bytes on disk, evicted-but-rebuildable, or
/// known-absent.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ResidencyState {
    Resident,
    EvictedCovered,
    Absent,
}

/// Recipe verification grade (D25); `failed` recipes are poisoned and
/// never surface as routes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum RouteVerify {
    Pending,
    Verified,
    ReplayedLocal,
}

/// 1G1R selection mode (D57): `strict` is a pure function of
/// (dat, preferences); `held_first` prefers what you actually have.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum OneGOneRMode {
    Strict,
    HeldFirst,
}

/// MAME set rendering mode (D31 deferred set).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "kebab-case")]
pub enum MameMode {
    NonMerged,
    Split,
    Merged,
}

// ---- GET /v1/auth/whoami ----

/// Whoami is open by design: it answers `authenticated: false` instead
/// of 401 so the SPA can probe without special-casing errors.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct WhoamiResponse {
    pub authenticated: bool,
    /// Absent for loopback (no user row) and anonymous callers.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// Absent when unauthenticated.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub role: Option<Role>,
    /// Absent when unauthenticated.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub via: Option<Via>,
}

// ---- POST /v1/auth/login + /v1/auth/invite/accept ----

/// Login credentials. Fields are `Option` so the handler owns the
/// "missing field" 400 (the D69 refactor preserves the wire behavior
/// exactly); the contract still marks them required.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct LoginRequest {
    #[schema(required = true)]
    pub username: Option<String>,
    #[schema(required = true)]
    pub password: Option<String>,
}

/// Invite acceptance: consumes the invite atomically, creates the user
/// with the invite's role, and starts a session.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct InviteAcceptRequest {
    /// The invite token exactly as minted (the URL fragment).
    #[schema(required = true)]
    pub token: Option<String>,
    /// 1-32 characters of `[a-z0-9_-]`.
    #[schema(required = true)]
    pub username: Option<String>,
    /// At least 8 characters.
    #[schema(required = true)]
    pub password: Option<String>,
}

/// A fresh login/acceptance answer: whoami-shaped plus the session
/// expiry. The session token itself rides the `Set-Cookie` header
/// (HttpOnly), never the body.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct SessionResponse {
    pub authenticated: bool,
    pub username: String,
    pub role: Role,
    /// Unix seconds.
    pub expires_at: i64,
}

// ---- GET /v1/systems ----

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct SystemsResponse {
    pub systems: Vec<System>,
}

/// A "system" is a `dat_source` row. `id` is a cache.db surrogate —
/// stable while the cache lives, re-minted by `datboi recover`;
/// clients treat it as a handle, not an identity (the durable identity
/// is provider/system).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct System {
    pub id: i64,
    pub provider: String,
    pub system: String,
    /// `provider/system`, the durable display identity.
    pub source: String,
    /// Null when the source exists but nothing was imported yet.
    #[schema(required = true)]
    pub revision: Option<Revision>,
    pub counts: Counts,
    /// Total entries in the current revision (counts sum to this).
    pub total: i64,
    /// Stored ViewDef names referencing this source.
    pub views: Vec<String>,
}

/// One imported dat revision.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct Revision {
    pub id: i64,
    #[schema(required = true)]
    pub version: Option<String>,
    #[schema(required = true)]
    pub date: Option<String>,
    /// Unix seconds.
    #[schema(required = true)]
    pub imported_at: Option<i64>,
}

/// The D39 entry-audit rollup, bucketed into the 4-state vocabulary.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct Counts {
    pub verified: i64,
    pub claimed: i64,
    pub missing: i64,
    pub nodump: i64,
}

// ---- GET /v1/systems/{id}/entries ----

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct EntriesPage {
    pub entries: Vec<EntryRow>,
    /// The FILTERED count; the offset/limit window slides under it.
    pub total: i64,
    pub offset: u64,
    pub limit: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct EntryRow {
    pub name: String,
    pub state: EntryState,
    /// Total required bytes — null unless every required claim
    /// declares a size.
    #[schema(required = true)]
    pub size: Option<i64>,
    /// Best hash of the single required claim, full hex — null when
    /// the entry wants zero or several ROMs (the detail endpoint has
    /// them all).
    #[schema(required = true)]
    pub wanted_hash: Option<String>,
    /// `sha256` | `sha1` | `md5` | `crc32`, strongest available.
    #[schema(required = true)]
    pub wanted_hash_algo: Option<String>,
}

// ---- GET /v1/systems/{id}/entries/{name} ----

/// Entry detail is keyed by NAME (`UNIQUE(revision_id, name)` within a
/// revision; claim names are not unique — MAME sets repeat them).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct EntryDetail {
    pub name: String,
    pub state: EntryState,
    #[schema(required = true)]
    pub size: Option<i64>,
    #[schema(required = true)]
    pub wanted_hash: Option<String>,
    #[schema(required = true)]
    pub wanted_hash_algo: Option<String>,
    pub revision: Revision,
    pub roms: Vec<RomClaim>,
}

/// One rom claim with its rollup state and, when a local blob
/// satisfies it, the resolved blob + rebuild routes + pin list.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct RomClaim {
    pub name: String,
    #[schema(required = true)]
    pub size: Option<i64>,
    pub state: ClaimState,
    pub optional: bool,
    /// Declared digests, lowercase hex; only the algorithms the dat
    /// actually carries appear.
    pub hashes: RomHashes,
    /// The satisfying local blob (strong-basis links only, smallest
    /// hash wins) — omitted entirely when nothing satisfies the claim.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub blob: Option<BlobInfo>,
    /// Rebuild routes for the resolved blob; omitted when `blob` is.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub routes: Option<Vec<RouteInfo>>,
    /// Views whose CURRENT snapshots reference the resolved blob
    /// (D33: the tag is what pins); omitted when `blob` is.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pins: Option<Vec<String>>,
}

/// Declared claim digests (lowercase hex); absent algorithms are
/// omitted, not null.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct RomHashes {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub crc32: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub md5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sha1: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sha256: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct BlobInfo {
    /// blake3, lowercase hex.
    pub hash: String,
    pub residency: ResidencyState,
    /// Last full-hash store verification (ingest or scrub), unix
    /// seconds; the index records no method, so none is claimed.
    #[schema(required = true)]
    pub verified_at: Option<i64>,
}

/// One human-readable rebuild route: `verb ← sources` plus the
/// source-availability dot.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct RouteInfo {
    pub route: String,
    /// Every input blob currently resident.
    pub source_present: bool,
    pub verify: RouteVerify,
}

// ---- GET /v1/views (+ detail) ----

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ViewsResponse {
    pub views: Vec<ViewSummary>,
}

/// One view in the listing: the union of tagged views (things being
/// served) and stored ViewDefs (defined but maybe never evaluated).
/// Row/byte/created stats come from the decoded snapshot manifest; a
/// missing or undecodable snapshot just omits them — the listing must
/// not die of one damaged view.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ViewSummary {
    pub name: String,
    /// Current snapshot hash (blake3 hex); null when defined but never
    /// evaluated.
    #[schema(required = true)]
    pub snapshot: Option<String>,
    /// Null for tagged views whose definition was deleted.
    #[schema(required = true)]
    pub definition: Option<Definition>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rows: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bytes: Option<u64>,
    /// Snapshot creation time, unix seconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<u64>,
}

/// ViewDef summary: dat ref, 1G1R mode, profile, image params (D62).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct Definition {
    pub provider: String,
    pub system: String,
    pub template: String,
    #[schema(required = true)]
    pub one_g_one_r: Option<OneGOneR>,
    #[schema(required = true)]
    pub profile: Option<String>,
    #[schema(required = true)]
    pub image: Option<ImageParams>,
    #[schema(required = true)]
    pub mame_mode: Option<MameMode>,
}

/// 1G1R selection policy (D57).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct OneGOneR {
    pub mode: OneGOneRMode,
    pub regions: Vec<String>,
    pub langs: Vec<String>,
}

/// FAT32 image parameters from the ViewDef (D62).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ImageParams {
    pub cluster_size: u32,
    /// MBR partition table vs superfloppy.
    pub partition: bool,
    #[schema(required = true)]
    pub label: Option<String>,
}

/// GET /v1/views/{name}: the summary plus serve endpoints and mint
/// status.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ViewDetail {
    #[serde(flatten)]
    pub summary: ViewSummary,
    pub endpoints: Endpoints,
    /// Mint status when the definition carries image params; null when
    /// it does not.
    #[schema(required = true)]
    pub image: Option<ImageStatus>,
}

/// Relative serve endpoints; DAV is loopback-only in M5 (D68).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct Endpoints {
    pub http: String,
    pub dav: String,
}

/// D62 mint status: the `image/<name>` tag, when present, is a minted
/// FAT32 image for this view.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ImageStatus {
    pub minted: bool,
    /// blake3 hex of the minted image; omitted when unminted.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
    /// Image size; omitted when unminted, null when the blob row has
    /// no recorded size (outer/inner Option = absent/null).
    #[serde(skip_serializing_if = "Option::is_none")]
    #[schema(value_type = Option<u64>)]
    pub bytes: Option<Option<u64>>,
}

// ---- GET /v1/views/{name}/files ----

/// A page of the view's CURRENT snapshot manifest — the friend browse
/// surface (web spec §4.3).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ViewFilesPage {
    pub files: Vec<FileRow>,
    /// The FILTERED count; the offset/limit window slides under it.
    pub total: u64,
    pub offset: u64,
    pub limit: u64,
    /// The snapshot these rows came from (blake3 hex).
    pub snapshot: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct FileRow {
    /// Manifest path, `/`-separated.
    pub path: String,
    pub size: u64,
    /// blake3 hex of the file content.
    pub hash: String,
}

// ---- GET /v1/storage ----

/// Storage stats from the blob index — the same truth `datboi status`
/// reports, without an NFS metadata walk.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct StorageResponse {
    /// Data-namespace blobs in the index.
    pub blob_count: i64,
    /// Resident bytes.
    pub on_disk_bytes: i64,
    /// Resident + evicted-covered bytes (what the collection
    /// represents).
    pub represented_bytes: i64,
    /// Resident bytes with no non-failed rebuild route — the "can't
    /// shrink yet" tax.
    pub literal_only_bytes: i64,
    pub quarantine: Quarantine,
}

/// D49 rule 3: components whose seek path produced bad bytes.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct Quarantine {
    pub count: u64,
    pub items: Vec<QuarantineItem>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct QuarantineItem {
    /// Component blob hash (blake3 hex).
    pub component: String,
    /// Unix seconds.
    pub quarantined_at: i64,
    pub reason: String,
}

// ---- GET /v1/jobs ----

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct JobsResponse {
    pub jobs: Vec<Job>,
}

/// Placeholder: the daemon has no job registry — ingest/scrub/eviction
/// run as CLI processes today (docs/open-questions.md, "Jobs tray
/// backend"), so the list is always empty and no job shape is
/// specified yet. Nothing here fakes progress.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct Job {}

// ---- GET /v1/admin/users ----

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct AdminUsersResponse {
    pub users: Vec<UserRow>,
    /// PENDING invites only: consumed ones live on as the user's
    /// provenance, expired ones are dead weight the UI need not show.
    pub invites: Vec<InviteRow>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct UserRow {
    pub username: String,
    pub role: Role,
    /// Unix seconds.
    pub created_at: i64,
    /// Granted view names (D68 ACL rows).
    pub grants: Vec<String>,
    /// Live (unexpired) session count.
    pub sessions: u64,
}

/// A pending invite. Only `blake3(token)` is stored — the token itself
/// appeared exactly once, in the mint response's fragment URL.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct InviteRow {
    /// blake3 of the token string, lowercase hex — the revocation key.
    pub token_hash: String,
    pub role: Role,
    /// Unix seconds.
    pub expires_at: i64,
    /// Minting username; null for loopback/CLI mints (no user row).
    #[schema(required = true)]
    pub created_by: Option<String>,
}

// ---- POST /v1/admin/invites ----

/// Invite mint parameters. `role` is a string on the Rust side so the
/// handler owns the "role must be owner or friend" 400 (unknown
/// variants must not become extractor 422s); the contract documents
/// the enum.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct InviteMintRequest {
    /// Defaults to `friend`.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[schema(value_type = Option<Role>)]
    pub role: Option<String>,
    /// 1-365; defaults to 7 (D68) — an effectively-eternal invite is a
    /// standing credential, which is what invites exist to avoid.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_days: Option<i64>,
}

/// The mint answer: a fragment URL (`/invite#<token>`) so the token
/// never appears in server logs or Referer headers.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct InviteMintResponse {
    pub url_path: String,
    /// Unix seconds.
    pub expires_at: i64,
}

// ---- POST /v1/admin/grants ----

/// Grant a friend a view (D68). Same Option-for-400 convention as the
/// auth requests; both fields are contractually required.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct GrantAddRequest {
    #[schema(required = true)]
    pub username: Option<String>,
    #[schema(required = true)]
    pub view: Option<String>,
}

// ---- DELETE /v1/admin/sessions/{username} ----

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct SessionsRevokedResponse {
    /// Sessions deleted.
    pub revoked: u64,
}

// ---- spec emission ----

/// The /v1 contract as an OpenAPI 3.1 document (operations live in
/// [`paths`]; utoipa collects referenced schemas transitively).
#[must_use]
pub fn openapi() -> utoipa::openapi::OpenApi {
    paths::openapi()
}

/// The spec as STABLE JSON: round-tripped through `serde_json::Value`
/// (BTreeMap-backed maps ⇒ keys sort), pretty-printed, trailing
/// newline. Byte-for-byte reproducible — the staleness test and the
/// checked-in `openapi.json` both depend on exactly this rendering.
#[must_use]
pub fn openapi_json() -> String {
    let value = serde_json::to_value(openapi()).expect("spec serializes");
    let mut out = serde_json::to_string_pretty(&value).expect("spec serializes");
    out.push('\n');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The checked-in spec IS the contract artifact (D69): a stale
    /// copy means the types moved without the spec (and the TS client
    /// generated from it) moving too — red suite, not a hand step.
    #[test]
    fn checked_in_spec_is_current() {
        let checked_in = include_str!("../openapi.json");
        let generated = openapi_json();
        assert!(
            checked_in == generated,
            "crates/datboi-api/openapi.json is stale: \
             run `cargo run -p datboi-api --bin datboi-gen-openapi` and commit the result"
        );
    }

    #[test]
    fn spec_covers_every_v1_operation() {
        let spec: serde_json::Value = serde_json::from_str(&openapi_json()).expect("parse");
        let paths = spec["paths"].as_object().expect("paths");
        for path in [
            "/v1/auth/whoami",
            "/v1/auth/invite/accept",
            "/v1/auth/login",
            "/v1/auth/logout",
            "/v1/systems",
            "/v1/systems/{id}/entries",
            "/v1/systems/{id}/entries/{name}",
            "/v1/views",
            "/v1/views/{name}",
            "/v1/views/{name}/files",
            "/v1/views/{name}/image",
            "/v1/storage",
            "/v1/jobs",
            "/v1/admin/users",
            "/v1/admin/invites",
            "/v1/admin/invites/{token_hash}",
            "/v1/admin/grants",
            "/v1/admin/grants/{username}/{view}",
            "/v1/admin/sessions/{username}",
        ] {
            assert!(paths.contains_key(path), "spec is missing {path}");
        }
        assert_eq!(spec["openapi"], "3.1.0", "OpenAPI 3.1 (D69)");
        // Both credential presentations are declared (D68).
        let schemes = spec["components"]["securitySchemes"]
            .as_object()
            .expect("securitySchemes");
        assert!(schemes.contains_key("session_cookie"));
        assert!(schemes.contains_key("bearer_token"));
    }

    /// The omitted-vs-null distinctions the handlers rely on.
    #[test]
    fn wire_shapes_match_the_handlers() {
        let whoami = WhoamiResponse {
            authenticated: false,
            username: None,
            role: None,
            via: None,
        };
        assert_eq!(
            serde_json::to_string(&whoami).expect("json"),
            r#"{"authenticated":false}"#,
            "absent identity fields are OMITTED, not null"
        );
        let unminted = ImageStatus {
            minted: false,
            hash: None,
            bytes: None,
        };
        assert_eq!(
            serde_json::to_string(&unminted).expect("json"),
            r#"{"minted":false}"#
        );
        let sizeless = ImageStatus {
            minted: true,
            hash: Some("ab".into()),
            bytes: Some(None),
        };
        assert_eq!(
            serde_json::to_string(&sizeless).expect("json"),
            r#"{"minted":true,"hash":"ab","bytes":null}"#,
            "minted-but-sizeless renders bytes as null, not absent"
        );
        // Detail flattening: ViewDetail serializes summary fields at
        // the top level (the wire shape view_json always had).
        let detail = ViewDetail {
            summary: ViewSummary {
                name: "gba".into(),
                snapshot: None,
                definition: None,
                rows: None,
                bytes: None,
                created_at: None,
            },
            endpoints: Endpoints {
                http: "/view/gba/".into(),
                dav: "/dav/gba/".into(),
            },
            image: None,
        };
        let v = serde_json::to_value(&detail).expect("json");
        assert_eq!(v["name"], "gba");
        assert_eq!(v["image"], serde_json::Value::Null);
        assert!(v.get("summary").is_none(), "flattened, not nested");
    }
}
