//! The /v1 API contract (D69): one typed struct per operation shape.
//!
//! This is the ONLY crate where serde/utoipa derives are legal. The
//! house no-derive rule exists because CAS object encodings ARE
//! identities (D18) — a macro must never own load-bearing bytes; D69
//! scopes that ban to canonical/content-addressed encodings. The HTTP
//! API is not that: it is a versioned, negotiable surface, so it gets
//! real types, and three consumers hang off them — the daemon's
//! handlers (datboi-server), the CHECKED-IN OpenAPI 3.1 spec
//! (`openapi.json`, regenerated by
//! `cargo run -p datboi-api --bin datboi-gen-openapi`, pinned byte-for-byte
//! by a test in this crate), and the web UI's generated TS client.
//!
//! Contract scope is exactly `/v1`. The minted-image download
//! (`GET /v1/views/{name}/image`) is in scope as an octet-stream
//! operation; the non-/v1 surfaces — the `/view/*` and `/snap/*` byte
//! trees (HTML/JSON listings, Range serving), `/dav`, NFS, and the
//! embedded UI fallback — are serving surfaces, not API operations,
//! and deliberately stay out of the spec.
//!
//! Field-level fidelity rule: these structs describe what actually
//! goes over the wire TODAY, and the wire mode rides the field's TYPE
//! (see [`wire`]): always-present-but-nullable is [`Nullable<T>`];
//! omitted-when-absent is `Option<T>` with
//! `#[serde(skip_serializing_if = "Option::is_none")]`.

use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

mod paths;
pub mod wire;

pub use wire::Nullable;

// ---- the uniform error shape ----

/// Every /v1 error body: `{"error": "<message>", "code": "<code>"}`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ApiError {
    /// Human-readable failure description — diagnostic detail for CLI
    /// and log consumers. The web UI presents `code`, not this.
    pub error: String,
    /// Machine-readable failure category (D77).
    pub code: ErrorCode,
}

/// Machine-readable failure category (D77). A CLOSED union: the web UI
/// maps every variant to a translated message through an exhaustive
/// switch, so adding a variant here fails the web typecheck until that
/// message exists — errors are translatable by construction, never by
/// passing English prose through.
///
/// The HTTP status derives FROM the code ([`ErrorCode::http_status`]),
/// so a handler cannot pair a code with a contradicting status.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ErrorCode {
    /// Malformed request shape or parameter values. The UI validates
    /// before sending, so reaching this implies a bug or a hand-built
    /// request — the `error` detail matters more than usual.
    BadRequest,
    /// The staged-upload token is unknown or expired: the fix is to
    /// upload again, and the UI should say so.
    UploadExpired,
    /// Authentication required (no/dead session, or a loopback-only
    /// surface reached from elsewhere).
    Unauthorized,
    /// Login refused: bad username or password — a typed answer, never
    /// session death.
    InvalidCredentials,
    /// Authenticated, but this resource is owner-only.
    OwnerOnly,
    /// The invite token is invalid, already spent, or expired.
    InvalidInvite,
    /// The Fetch-Metadata CSRF gate rejected a cross-origin request.
    CsrfRejected,
    /// The requested resource does not exist.
    NotFound,
    /// Invite acceptance raced a name: that username is taken.
    UsernameTaken,
    /// A conflicting maintenance task holds the guard; retry shortly.
    Busy,
    /// The store lacks headroom for the declared upload size.
    StoreFull,
    /// The daemon failed internally; the `error` detail is diagnostic.
    Internal,
}

impl ErrorCode {
    /// The one HTTP status this code rides — the pairing lives here so
    /// call sites cannot disagree about it.
    pub fn http_status(self) -> u16 {
        match self {
            Self::BadRequest | Self::UploadExpired => 400,
            Self::Unauthorized | Self::InvalidCredentials => 401,
            Self::OwnerOnly | Self::InvalidInvite | Self::CsrfRejected => 403,
            Self::NotFound => 404,
            Self::UsernameTaken => 409,
            Self::Busy => 503,
            Self::StoreFull => 507,
            Self::Internal => 500,
        }
    }
}

/// The `{"ok": true}` acknowledgement mutations answer with.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct OkResponse {
    pub ok: bool,
}

// ---- shared vocabulary enums (lowercase on the wire) ----

/// User roles (D30/D68): owners see everything, friends see grants.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    Owner,
    Friend,
}

/// How a caller's identity arrived (whoami reports it). `loopback` is
/// the D68 implicit owner — a local shell already owns the daemon's
/// files.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "lowercase")]
pub enum Via {
    Loopback,
    Session,
    Bearer,
}

/// The UI's 4-state per-entry vocabulary, derived from the D39 rollup
/// (web spec §7). `nodump` entries are excluded from completeness math
/// client-side.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "lowercase")]
pub enum EntryState {
    Verified,
    Claimed,
    Missing,
    Nodump,
}

/// Per-claim rollup state — the entry vocabulary plus the two
/// non-holding grades (`peer`, `probable`) that fold into `missing` at
/// entry granularity.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "lowercase")]
pub enum ClaimState {
    Verified,
    Claimed,
    Peer,
    Probable,
    Missing,
    Nodump,
}

/// Blob residency (D21): bytes on disk, evicted-but-rebuildable, or
/// known-absent.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum ResidencyState {
    Resident,
    EvictedCovered,
    Absent,
}

/// Recipe verification grade (D25); `failed` recipes are poisoned and
/// never surface as routes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum RouteVerify {
    Pending,
    Verified,
    ReplayedLocal,
}

/// 1G1R selection mode (D57): `strict` is a pure function of
/// (dat, preferences); `held_first` prefers what you actually have.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum OneGOneRMode {
    Strict,
    HeldFirst,
}

/// MAME set rendering mode (D31 deferred set).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "kebab-case")]
pub enum MameMode {
    NonMerged,
    Split,
    Merged,
}

// ---- GET /v1/auth/whoami ----

/// Whoami is open by design: it answers `authenticated: false` instead
/// of 401 so the SPA can probe without special-casing errors.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct WhoamiResponse {
    pub authenticated: bool,
    /// Absent for loopback (no user row) and anonymous callers.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// Absent when unauthenticated.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub role: Option<Role>,
    /// Absent when unauthenticated.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub via: Option<Via>,
}

// ---- POST /v1/auth/login + /v1/auth/invite/accept ----

/// Login credentials. Missing fields are the extractor's typed 400
/// (datboi-server's `ApiJson` keeps every body-parse failure in the
/// D69 error shape), so plain `String` IS the required-field contract.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct LoginRequest {
    pub username: String,
    pub password: String,
}

/// Invite acceptance: consumes the invite atomically, creates the user
/// with the invite's role, and starts a session.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct InviteAcceptRequest {
    /// The invite token exactly as minted (the URL fragment).
    pub token: String,
    /// 1-32 characters of `[a-z0-9_-]`.
    pub username: String,
    /// At least 8 characters.
    pub password: String,
}

/// A fresh login/acceptance answer: whoami-shaped plus the session
/// expiry. The session token itself rides the `Set-Cookie` header
/// (HttpOnly), never the body.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct SessionResponse {
    pub authenticated: bool,
    pub username: String,
    pub role: Role,
    /// Unix seconds.
    pub expires_at: i64,
}

// ---- GET /v1/systems ----

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct SystemsResponse {
    pub systems: Vec<System>,
}

/// A "system" is a `dat_source` row. `id` is a cache.db surrogate —
/// stable while the cache lives, re-minted by `datboi recover`;
/// clients treat it as a handle, not an identity (the durable identity
/// is provider/system).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct System {
    pub id: i64,
    pub provider: String,
    pub system: String,
    /// `provider/system`, the durable display identity.
    pub source: String,
    /// Null when the source exists but nothing was imported yet.
    pub revision: Nullable<Revision>,
    pub counts: Counts,
    /// Total entries in the current revision (counts sum to this).
    pub total: i64,
    /// Stored ViewDef names referencing this source.
    pub views: Vec<String>,
}

/// One imported dat revision.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct Revision {
    pub id: i64,
    pub version: Nullable<String>,
    pub date: Nullable<String>,
    /// Unix seconds.
    pub imported_at: Nullable<i64>,
}

/// The D39 entry-audit rollup, bucketed into the 4-state vocabulary.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct Counts {
    pub verified: i64,
    pub claimed: i64,
    pub missing: i64,
    pub nodump: i64,
}

// ---- GET /v1/systems/{id}/entries ----

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct EntriesPage {
    pub entries: Vec<EntryRow>,
    /// The FILTERED count; the offset/limit window slides under it.
    pub total: i64,
    pub offset: u64,
    pub limit: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct EntryRow {
    pub name: String,
    pub state: EntryState,
    /// Total required bytes — null unless every required claim
    /// declares a size.
    pub size: Nullable<i64>,
    /// Best hash of the single required claim, full hex — null when
    /// the entry wants zero or several ROMs (the detail endpoint has
    /// them all).
    pub wanted_hash: Nullable<String>,
    /// `sha256` | `sha1` | `md5` | `crc32`, strongest available.
    pub wanted_hash_algo: Nullable<String>,
}

// ---- GET /v1/systems/{id}/entries/{name} ----

/// Entry detail is keyed by NAME (`UNIQUE(revision_id, name)` within a
/// revision; claim names are not unique — MAME sets repeat them).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct EntryDetail {
    pub name: String,
    pub state: EntryState,
    pub size: Nullable<i64>,
    pub wanted_hash: Nullable<String>,
    pub wanted_hash_algo: Nullable<String>,
    pub revision: Revision,
    pub roms: Vec<RomClaim>,
}

/// One rom claim with its rollup state and, when a local blob
/// satisfies it, the resolved blob + rebuild routes + pin list.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct RomClaim {
    pub name: String,
    pub size: Nullable<i64>,
    pub state: ClaimState,
    pub optional: bool,
    /// Declared digests, lowercase hex; only the algorithms the dat
    /// actually carries appear.
    pub hashes: RomHashes,
    /// The satisfying local blob (strong-basis links only, smallest
    /// hash wins) — omitted entirely when nothing satisfies the claim.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub blob: Option<BlobInfo>,
    /// Rebuild routes for the resolved blob; omitted when `blob` is.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub routes: Option<Vec<RouteInfo>>,
    /// Views whose CURRENT snapshots reference the resolved blob
    /// (D33: the tag is what pins); omitted when `blob` is.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pins: Option<Vec<String>>,
}

/// Declared claim digests (lowercase hex); absent algorithms are
/// omitted, not null.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct RomHashes {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub crc32: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub md5: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sha1: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sha256: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct BlobInfo {
    /// blake3, lowercase hex.
    pub hash: String,
    pub residency: ResidencyState,
    /// Last full-hash store verification (ingest or scrub), unix
    /// seconds; the index records no method, so none is claimed.
    pub verified_at: Nullable<i64>,
}

/// One human-readable rebuild route: `verb ← sources` plus the
/// source-availability dot.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct RouteInfo {
    pub route: String,
    /// Every input blob currently resident.
    pub source_present: bool,
    pub verify: RouteVerify,
}

// ---- POST /v1/dats/import ----

/// One import's receipt — the same fields `datboi dat import --json`
/// prints, plus the resolved source identity (the web caller never saw
/// the dat header, so it can't derive provider/system itself).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct DatImportResponse {
    /// The dat source this landed in — the `/v1/systems` id.
    pub source_id: i64,
    pub revision_id: i64,
    /// blake3 of the dat blob now in the CAS, lowercase hex.
    pub dat_blob: String,
    /// Resolved provider (override, else derived from the dat header —
    /// homepage when it names an org, else author).
    pub provider: String,
    /// Resolved system (override, else the dat header's name).
    pub system: String,
    pub entries: u64,
    pub claims: u64,
    /// Revisions demoted to header-only by this import (D38).
    pub demoted_revisions: Vec<i64>,
}

// ---- POST /v1/dats/fetch (D16/D96 auto-fetch) ----

/// Fetch a dat over HTTP and import it (Redump auto-fetch, D16).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct DatFetchRequest {
    /// A full URL, or `redump/<system-slug>` (e.g. `redump/psx`).
    pub source: String,
    /// Provider override; `redump/...` defaults to "Redump", else the
    /// dat header decides.
    #[serde(default)]
    pub provider: Option<String>,
    /// System override; the dat header decides when absent.
    #[serde(default)]
    pub system: Option<String>,
}

/// A fetch receipt: the resolved URL that was fetched, plus the import
/// outcome (the artifact went through the normal import path — D15).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct DatFetchResponse {
    /// The URL actually fetched (a `redump/...` source resolves here).
    pub url: String,
    /// The import receipt for the fetched dat.
    pub import: DatImportResponse,
}

// ---- GET /v1/views (+ detail) ----

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ViewsResponse {
    pub views: Vec<ViewSummary>,
}

/// One view in the listing: the union of tagged views (things being
/// served) and stored ViewDefs (defined but maybe never evaluated).
/// Row/byte/created stats come from the decoded snapshot manifest; a
/// missing or undecodable snapshot just omits them — the listing must
/// not die of one damaged view.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ViewSummary {
    pub name: String,
    /// Current snapshot hash (blake3 hex); null when defined but never
    /// evaluated.
    pub snapshot: Nullable<String>,
    /// Null for tagged views whose definition was deleted.
    pub definition: Nullable<Definition>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rows: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bytes: Option<u64>,
    /// Snapshot creation time, unix seconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<u64>,
}

/// ViewDef summary: dat ref, 1G1R mode, profile, image params (D62).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct Definition {
    pub provider: String,
    pub system: String,
    pub template: String,
    pub one_g_one_r: Nullable<OneGOneR>,
    pub profile: Nullable<String>,
    pub image: Nullable<ImageParams>,
    pub mame_mode: Nullable<MameMode>,
}

/// 1G1R selection policy (D57).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct OneGOneR {
    pub mode: OneGOneRMode,
    pub regions: Vec<String>,
    pub langs: Vec<String>,
}

/// FAT32 image parameters from the ViewDef (D62).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ImageParams {
    pub cluster_size: u32,
    /// MBR partition table vs superfloppy.
    pub partition: bool,
    pub label: Nullable<String>,
}

/// GET /v1/view-profiles: the built-in constraint profiles a view
/// definition may name (the target-device limits an evaluation checks
/// against — docs/views.md). Static built-in data; the define UI offers
/// these as the `profile` choice.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ViewProfilesResponse {
    pub profiles: Vec<ViewProfile>,
}

/// One constraint profile. Mirrors `datboi-catalog`'s built-in `Profile`
/// (the CLI's `view profiles` renders the same three limits).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ViewProfile {
    pub name: String,
    /// Max bytes per path component (UTF-8).
    pub max_name_len: u64,
    /// Files larger than this don't fit the target at all; null = no
    /// ceiling (e.g. exFAT targets).
    pub max_file_size: Nullable<u64>,
    /// Directories with more children than this are reported; null = no
    /// limit enforced.
    pub max_dir_entries: Nullable<u64>,
}

/// PUT /v1/views/{name}: define or replace a view (D96 view authoring;
/// the CLI's `view define`). The name is the path segment — this body
/// is its definition. `one_g_one_r` and `mame_mode` are mutually
/// exclusive (families vs sets answer different questions); setting both
/// is a 400. Omitting all selection fields defines an all-entries view.
/// Mirrors the read-side [`Definition`], but with omittable optionals
/// (request convention: `T` for required, `Option<T>` + skip for
/// optional — see [`wire`]).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ViewDefineRequest {
    pub provider: String,
    pub system: String,
    /// Layout template. Placeholders `{entry}` / `{name}`; path
    /// separators inside expanded values are sanitized to `_`.
    pub template: String,
    /// `Some` = 1G1R over clone families with these priorities.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub one_g_one_r: Option<OneGOneR>,
    /// Built-in constraint profile name (see `GET /v1/view-profiles`).
    /// An unknown name is a 400.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub profile: Option<String>,
    /// `Some` = the view also reifies as a FAT32 image (D62).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub image: Option<ImageParams>,
    /// `Some` = render a MAME listxml source as merge-mode sets.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mame_mode: Option<MameMode>,
}

/// PUT /v1/views/{name} result: the stored definition, echoed back so
/// the UI can render the view without a follow-up read.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ViewDefineResponse {
    pub name: String,
    pub definition: Definition,
}

/// GET /v1/views/{name}: the summary plus serve endpoints and mint
/// status.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ViewDetail {
    #[serde(flatten)]
    pub summary: ViewSummary,
    pub endpoints: Endpoints,
    /// Mint status when the definition carries image params; null when
    /// it does not.
    pub image: Nullable<ImageStatus>,
}

/// Relative serve endpoints; DAV is loopback-only in M5 (D68).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct Endpoints {
    pub http: String,
    pub dav: String,
}

/// D62 mint status: the `image/<name>` tag, when present, is a minted
/// FAT32 image for this view.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ImageStatus {
    pub minted: bool,
    /// blake3 hex of the minted image; omitted when unminted.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
    /// Image size; omitted when unminted, null when the blob row has
    /// no recorded size (outer Option/inner Nullable = absent/null).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bytes: Option<Nullable<u64>>,
}

// ---- analyzer config (D60/D96): GET /v1/analyzers, PUT /v1/analyzers/{family} ----

/// The shipped analyzer families and their per-family config — the same
/// data the CLI's `analyzer list` prints (owner-only).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct AnalyzersResponse {
    pub analyzers: Vec<AnalyzerInfo>,
}

/// One family's enable state and opaque params. `params_hex` is the
/// analyzer-owned params (D60: the analyzer defines the encoding),
/// lowercase hex; null when unset.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct AnalyzerInfo {
    pub family: String,
    pub enabled: bool,
    pub params_hex: Nullable<String>,
}

/// PUT /v1/analyzers/{family}: set a family's full config. `enabled`
/// toggles the opt-out flag; `params_hex` is an even-length hex string
/// (an odd or non-hex value is a 400), or null to clear.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct AnalyzerConfigRequest {
    pub enabled: bool,
    pub params_hex: Nullable<String>,
}

// ---- GET /v1/views/{name}/files ----

/// A page of the view's CURRENT snapshot manifest — the friend browse
/// surface (web spec §4.3).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ViewFilesPage {
    pub files: Vec<FileRow>,
    /// The FILTERED count; the offset/limit window slides under it.
    pub total: u64,
    pub offset: u64,
    pub limit: u64,
    /// The snapshot these rows came from (blake3 hex).
    pub snapshot: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct FileRow {
    /// Manifest path, `/`-separated.
    pub path: String,
    pub size: u64,
    /// blake3 hex of the file content.
    pub hash: String,
}

// ---- GET /v1/storage ----

/// Storage stats from the blob index — the same truth `datboi status`
/// reports, without an NFS metadata walk.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct StorageResponse {
    /// Data-namespace blobs in the index.
    pub blob_count: i64,
    /// Resident bytes.
    pub on_disk_bytes: i64,
    /// Resident + evicted-covered bytes (what the collection
    /// represents).
    pub represented_bytes: i64,
    /// Resident bytes with no non-failed rebuild route — the "can't
    /// shrink yet" tax.
    pub literal_only_bytes: i64,
    pub quarantine: Quarantine,
    /// Newest finished scrub from the D74 ledger; null before the
    /// first recorded run.
    pub last_scrub: Nullable<LastScrub>,
}

/// The scrub-run ledger readout (D74 rows, kind scrub).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct LastScrub {
    /// Unix seconds the run finished.
    pub finished_at: i64,
    /// The run's ledger name (carries the sample %).
    pub name: String,
}

/// D49 rule 3: components whose seek path produced bad bytes.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct Quarantine {
    pub count: u64,
    pub items: Vec<QuarantineItem>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct QuarantineItem {
    /// Component blob hash (blake3 hex).
    pub component: String,
    /// Unix seconds.
    pub quarantined_at: i64,
    pub reason: String,
}

// ---- GET /v1/storage/breakdown ----

/// Where the bytes live: the debug-grade aggregate behind the storage
/// screen — per-(namespace, residency) accounting, dat-source
/// attribution, and the largest blobs.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct StorageBreakdown {
    pub by_class: Vec<ClassBytes>,
    pub by_source: Vec<SourceBytes>,
    /// Top 50 data-namespace blobs by size.
    pub largest: Vec<BlobRow>,
}

/// One (namespace, residency) cell of the blob index.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ClassBytes {
    /// `data` | `meta` (D20).
    pub namespace: String,
    pub residency: ResidencyState,
    pub blobs: i64,
    /// SUM(size) with NULL sizes counted as 0; `sizeless` says how many.
    pub bytes: i64,
    /// Blobs in this cell with no recorded size.
    pub sizeless: i64,
}

/// Data-namespace bytes attributed to one dat source via identity
/// links (identity_blob → rom_claim → entry → the source's CURRENT
/// dat_revision). A blob claimed by several sources counts in EACH
/// row — the column does not sum to the store. Blobs with no identity
/// link at all fold into the `(unattributed)` row.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct SourceBytes {
    /// `provider/system`, or `(unattributed)`.
    pub source: String,
    pub blobs: i64,
    pub bytes: i64,
}

// ---- GET /v1/blobs ----

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct BlobsPage {
    pub blobs: Vec<BlobRow>,
    /// The FILTERED count; the offset/limit window slides under it.
    pub total: i64,
    pub offset: u64,
    pub limit: u64,
}

/// One blob-index row with its graph degree — enough to answer "what
/// is this?" at listing granularity (`GET /v1/blobs/{hash}` expands
/// the edges).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct BlobRow {
    /// blake3, lowercase hex.
    pub hash: String,
    pub size: Nullable<i64>,
    /// `data` | `meta` (D20).
    pub namespace: String,
    pub residency: ResidencyState,
    /// Last full-hash store verification, unix seconds.
    pub verified_at: Nullable<i64>,
    /// source_file provenance rows naming this blob.
    pub sources: u64,
    /// Non-poisoned recipes producing it (D25: `failed` never counts).
    pub routes_in: u64,
    /// Non-poisoned recipes consuming it.
    pub routes_out: u64,
}

// ---- GET /v1/blobs/{hash} ----

/// The blob inspector: identity, digests, provenance, the one-hop
/// recipe-DAG neighborhood, satisfied claims, and pinning views. The
/// listing row's degree counts materialize here as the actual lists
/// (claims capped at 100 — `claims_total` is uncapped).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct BlobDetail {
    /// blake3, lowercase hex.
    pub hash: String,
    pub size: Nullable<i64>,
    /// `data` | `meta` (D20).
    pub namespace: String,
    pub residency: ResidencyState,
    pub verified_at: Nullable<i64>,
    pub digests: BlobDigests,
    pub provenance: Vec<ProvenanceRow>,
    /// Source paths carried by recipe-CONNECTED blobs (D79 viral
    /// provenance display): where these bytes actually arrived, for
    /// derived/member blobs whose own `provenance` is empty. Capped
    /// at 10.
    pub provenance_via: Vec<ProvenanceViaRow>,
    /// Recipes whose OUTPUT is this blob — ways to make it.
    pub routes_in: Vec<RouteEdge>,
    /// Recipes consuming this blob as an input — things made from it.
    pub routes_out: Vec<RouteEdge>,
    /// Capped at 100 rows; `claims_total` is the uncapped count.
    pub claims: Vec<ClaimRef>,
    pub claims_total: u64,
    /// Claimed blobs this blob is connected to through the recipe DAG
    /// (D79): the display identity when `claims` is empty. Capped at
    /// 20; empty for a truly unattached blob.
    pub roots: Vec<RootRef>,
    /// Magic-byte sniff of resident bytes ("zip archive", …) — a
    /// display hint, never identity (D18: type lives in the edges).
    /// Null when absent from disk or unrecognized.
    pub sniff: Nullable<String>,
    /// Views whose CURRENT snapshot references this blob (D33: the tag
    /// is what pins).
    pub pins: Vec<String>,
}

/// A claimed root reachable from a blob through recipe edges (D79).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct RootRef {
    /// The root blob (blake3 hex) — links into its own inspector.
    pub hash: String,
    /// Best claim name on the root.
    pub entry: String,
    /// provider/system of that claim.
    pub source: String,
    pub relation: RootRelation,
}

/// How the inspected blob relates to a claimed root, following
/// DIRECTED recipe edges (input → output = "helps make").
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum RootRelation {
    /// The blob is an upstream ingredient: some recipe chain assembles
    /// the root FROM it (chunks, containers, preflate streams).
    Makes,
    /// The blob is a downstream product of the root (stripped bodies,
    /// extracted variants).
    DerivedFrom,
    /// Connected through the DAG but on a sibling branch (e.g. a chunk
    /// of rom A reaching rom B through their shared container).
    Related,
}

/// One viral-provenance row (D79): a source path recorded on a
/// recipe-connected blob, shown on blobs that have none of their own.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ProvenanceViaRow {
    pub path: String,
    /// When the path was last scanned/ingested, unix seconds.
    pub ingested_at: Nullable<i64>,
    /// The connected blob (blake3 hex) actually carrying the path.
    pub via: String,
}

/// Every digest the index holds for the blob's bytes: the blake3 key
/// plus recorded alias digests (D22). The declared CHD sha1 alias is
/// excluded — it attests decompressed content, not these bytes (D44).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct BlobDigests {
    /// The identity, lowercase hex.
    pub blake3: String,
    #[serde(flatten)]
    pub aliases: RomHashes,
}

/// One rescan-cache row: a filesystem path that hashed to this blob.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ProvenanceRow {
    pub path: String,
    /// When the path was last scanned/ingested, unix seconds.
    pub ingested_at: Nullable<i64>,
}

/// One recipe edge of the DAG neighborhood, navigable — every
/// [`HashRef`] resolves at `GET /v1/blobs/{hash}`. Poisoned (`failed`)
/// recipes never surface (D25 terminal).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct RouteEdge {
    /// The op as recorded: builtin `name@major`, wasm `<hex>#export`.
    pub op: String,
    pub verify: RouteVerify,
    pub inputs: Vec<HashRef>,
    pub outputs: Vec<HashRef>,
}

/// A blob reference inside a route edge.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct HashRef {
    /// blake3, lowercase hex.
    pub hash: String,
    pub size: Nullable<i64>,
    /// The recipe_output member name (or recipe_input role), when
    /// recorded.
    pub name: Nullable<String>,
}

/// One dat claim this blob satisfies, via identity links of any
/// evidence grade (current revisions only).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ClaimRef {
    /// Entry name within the source's current revision.
    pub entry: String,
    /// `provider/system` display identity.
    pub source: String,
}

// ---- POST /v1/ingest/uploads ----

/// One staged upload's receipt.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct UploadResponse {
    /// Opaque staging token — spend it in `POST /v1/ingest`. Tokens
    /// are in-memory: a daemon restart forgets them (the staged bytes
    /// are swept with the rest of the store's tmp/).
    pub upload: String,
    /// Bytes received and staged.
    pub bytes: u64,
}

// ---- POST /v1/ingest ----

/// Start an ingest job over staged uploads.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct IngestRequest {
    /// Staging tokens from `POST /v1/ingest/uploads`, spent
    /// all-or-nothing.
    pub uploads: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct IngestStartResponse {
    /// Poll `GET /v1/jobs/{id}` for progress and the report.
    pub job: i64,
}

// ---- POST /v1/blobs/{hash}/verify (D80) ----

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct VerifyStartResponse {
    /// Poll `GET /v1/jobs/{id}`; done stamps `verified_at`, failed
    /// carries the corruption evidence in `error`.
    pub job: i64,
}

/// A started background job (D96 view verbs: eval, mint; maintenance
/// verbs: scrub). Poll `GET /v1/jobs/{id}` for progress; the finished
/// job's report carries the outcome, a failed one carries `error`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct JobStartResponse {
    pub job: i64,
}

// ---- POST /v1/scrub (D96 maintenance) ----

/// Trigger a corpus scrub over serve — the same walk `datboi scrub`
/// runs (verify bytes against names, back-fill aliases + `verified_at`,
/// pack integrity, optional recipe rehabilitation). Long-running, so it
/// answers a `JobStartResponse`; the finished Scrub job's notes carry
/// the checked/refreshed/corrupt/missing summary.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ScrubRequest {
    /// Percentage of loose blobs to check (deterministic sample by hash
    /// prefix); packs are always scrubbed whole when this is non-zero.
    /// Defaults to 100 (a full pass), matching the CLI.
    #[serde(default)]
    pub sample_pct: Option<u8>,
    /// Re-execute poisoned (Failed) recipes; a verified re-replay clears
    /// the poison. Defaults to false.
    #[serde(default)]
    pub rehabilitate: Option<bool>,
}

// ---- POST /v1/sweep (D96 on-demand refinement) ----

/// Run one analyzer sweep round on demand — the manual equivalent of the
/// ambient refiner's per-family drain (D71). Long-running (a preflate
/// split is minutes), so it answers a `JobStartResponse`; the finished
/// Refine job's note carries the enqueued/analyzed/positive/negative
/// counts and the remaining queue depth.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct SweepRequest {
    /// Analyzer name (canonical or CLI alias): noop, chunk, preflate,
    /// ecm, nds, narc.
    pub analyzer: String,
    /// Maximum items to analyze this round. Defaults to 10000 (the CLI
    /// default).
    #[serde(default)]
    pub limit: Option<u64>,
}

// ---- POST /v1/snapshot (D75/D96 manual trigger) ----

/// The report of one minted state snapshot — the same numbers `datboi
/// snapshot` prints. Content-dedup means an unchanged shard costs no new
/// batch blob, so `new_batch_blobs` is the actual write amplification.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct SnapshotResponse {
    /// The minted snapshot object's blake3 (64 hex chars).
    pub hash: String,
    /// Monotonic snapshot sequence number.
    pub sequence: i64,
    /// Dat sources captured.
    pub sources: u64,
    /// Alias rows batched across the shard fanout.
    pub alias_rows: u64,
    /// Analysis rows batched.
    pub analysis_rows: u64,
    /// Batch blobs newly written this mint (unchanged shards dedup away).
    pub new_batch_blobs: u64,
}

// ---- POST /v1/evict (D72/D96 on-demand eviction) ----

/// Reclaim resident bytes by evicting recipe-covered literals (D25/D72).
/// `dry_run` reports the plan without deleting (the preview surface);
/// otherwise the drop runs under the D72 singleton guard as a background
/// Gc job — a 202 with a job id, or a 503 if the guard is already held.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct EvictRequest {
    /// Evict until at most this many resident bytes remain.
    pub target_bytes: u64,
    /// License (replay) covered routes first, so routes that have not
    /// yet replayed on this host become evictable too. Defaults to false.
    #[serde(default)]
    pub license: Option<bool>,
    /// Report the plan without deleting anything. Defaults to false.
    #[serde(default)]
    pub dry_run: Option<bool>,
}

/// One candidate the plan cannot drop right now, with the D25/D27 reasons
/// spelled out (a residency planner that says "0 evicted" without saying
/// why loses trust).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct EvictBlocked {
    pub hash: String,
    pub reasons: Vec<String>,
}

/// The dry-run eviction plan: what would drop, and what is held back.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct EvictPlan {
    /// Blobs that would be evicted at the current target.
    pub evictable: u64,
    /// Bytes those evictions would reclaim.
    pub reclaimable_bytes: u64,
    /// Candidates held back, each with its reasons.
    pub blocked: Vec<EvictBlocked>,
}

// ---- GET /v1/jobs (+ /{id}) ----

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct JobsResponse {
    pub jobs: Vec<Job>,
}

/// What a job is doing. Under D96 the expensive view verbs graduated to
/// background jobs on the serve surface (eval, mint); evict/sweep follow.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "lowercase")]
pub enum JobKind {
    Ingest,
    /// A refinement drain (D71): the daemon's ambient analyzer worker
    /// chewing through one family's sweep queue. `files_*`/`bytes_*`
    /// in the detail count ITEMS (blobs), not files/bytes.
    Refine,
    /// GC-family maintenance (D72/D73): licensing drains, watermark
    /// evictions, orphan applies. Item counts, like refine.
    Gc,
    /// A scrub pass (CLI-recorded via the D74 ledger; the run ledger
    /// the storage screen wants).
    Scrub,
    /// A view evaluation → immutable snapshot (D96): the CLI's `view
    /// eval`, run as a background job on the serve surface.
    Eval,
    /// A FAT32 image mint for a view (D62/D96): the CLI's `view image`.
    Mint,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
#[serde(rename_all = "lowercase")]
pub enum JobRunState {
    Running,
    Done,
    Failed,
}

/// One row of the job registry (running + D74 ledger history — the
/// activity page render, D82).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct Job {
    pub id: i64,
    /// Display name, e.g. `ingest — 3 files`.
    pub name: String,
    /// 0–100, byte-weighted at FILE granularity (the pipeline reports
    /// no intra-file progress); clamped to 99 while running so only a
    /// finished job reads 100.
    pub progress: u8,
    pub kind: JobKind,
    pub state: JobRunState,
    /// Unix seconds. On the LIST row, not just the detail, because the
    /// activity page renders relative timestamps for every row and
    /// must not need N+1 detail fetches to do it (D82).
    pub started_at: i64,
    /// Unix seconds; null while running.
    pub finished_at: Nullable<i64>,
}

/// GET /v1/jobs/{id}: the row plus counters and the (growing, then
/// final) report. File paths in the report are the CLIENT's original
/// names — staging paths never leak.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct JobDetail {
    #[serde(flatten)]
    pub job: Job,
    pub files_total: u64,
    pub files_done: u64,
    pub bytes_total: u64,
    pub bytes_done: u64,
    /// Original name of the file being processed; omitted between
    /// files and once finished.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub current: Option<String>,
    // started_at / finished_at moved onto the flattened `Job` row —
    // this struct's JSON shape is unchanged.
    /// Cumulative across completed files — grows while running, final
    /// when done.
    pub report: IngestReportBody,
    /// Entries this job's content NEWLY satisfied (the shelf lights).
    /// Capped at 200 rows; `matched_total` is the uncapped count.
    pub matched: Vec<MatchedEntry>,
    pub matched_total: u64,
    /// Infrastructure failure only; per-file refusals live in the
    /// report.
    pub error: Nullable<String>,
}

// ---- GET /v1/gc/orphans (+ keep / apply) ----

/// One reviewable orphan (D73): unreferenced past the grace window,
/// still unrooted as of the last sweep. The mark is REVIEW state —
/// apply re-verifies reachability at delete time.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct OrphanItem {
    pub hash: String,
    pub size: u64,
    /// Unix seconds of first-observed-unreferenced (the grace clock).
    pub marked_at: i64,
    /// Ingest paths that ever carried these bytes — the context a
    /// reviewer needs to say junk-or-keep.
    pub sources: Vec<String>,
    /// Operator keep-mark: excluded from apply until unkept.
    pub kept: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct OrphansResponse {
    pub orphans: Vec<OrphanItem>,
    /// Bytes across non-kept candidates (what apply-all would free).
    pub reclaimable_bytes: u64,
    pub grace_secs: i64,
}

/// Set or clear a keep-mark ("this is not junk").
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct GcKeepRequest {
    pub hash: String,
    pub keep: bool,
}

/// Apply the reviewed set (D73: the ONE human-triggered destructive
/// action). Absent `hashes` = every reviewable, non-kept candidate.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct GcApplyRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hashes: Option<Vec<String>>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct GcApplyResponse {
    pub deleted: u64,
    pub bytes_reclaimed: u64,
    /// Requested but refused at delete-time re-verification (rooted
    /// since review, kept, or not aged) — never an error, always
    /// visible.
    pub skipped: u64,
}

// ---- GC policy (D72/D73/D96): GET + PUT /v1/gc/config ----

/// The eviction/GC policy: high/low watermarks (canonical `off` / `NN%`
/// / absolute-bytes strings) and the orphan grace window in seconds.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct GcConfig {
    pub high_water: String,
    pub low_water: String,
    pub grace_secs: i64,
}

/// PUT /v1/gc/config: set any subset of the policy. Each omitted field
/// is left unchanged; a malformed watermark or negative grace is a 400.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct GcConfigRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub high_water: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub low_water: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub grace_secs: Option<i64>,
}

/// One dat entry an ingest job newly satisfied — the user-vocabulary
/// half of the report (games, not blob counts).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct MatchedEntry {
    pub name: String,
    /// `provider/system` display identity.
    pub source: String,
}

/// The ingest pipeline's report (datboi-ingest `IngestReport`), as
/// wire JSON. Same counters the CLI prints.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct IngestReportBody {
    pub files_scanned: u64,
    /// Rescan-cache hits: same path, mtime, and size as last time.
    pub files_unchanged: u64,
    /// New blobs stored.
    pub files_stored: u64,
    /// Content already in the store (dupes).
    pub files_already_present: u64,
    pub chd_v5: u64,
    /// Zip members claimed in place (the container stays the literal).
    pub members_claimed: u64,
    /// 7z/rar members extracted as resident blobs.
    pub members_extracted: u64,
    pub detector_hits: u64,
    /// Files over the skipper sniff cap — stored, but not
    /// detector-checked.
    pub skipper_skipped_large: u64,
    /// Files the job classified (by content) as dats — loose or the
    /// sole member of a zip — and imported instead of ingesting. Its
    /// own lane: pipeline counters above stay pure, a dat import is
    /// not a `files_scanned`.
    pub dats_imported: Vec<DatImportedItem>,
    pub errors: Vec<IngestErrorItem>,
    pub member_skips: Vec<IngestMemberSkipItem>,
    pub notes: Vec<String>,
}

/// One dat an ingest job imported (the unified drop surface: content
/// classifies each file as dat / zipped dat / ROM — names never
/// decide).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct DatImportedItem {
    /// The client's original name for the file.
    pub path: String,
    /// Resolved provider/system — the `/v1/systems` identity the dat
    /// landed in (the caller never saw the dat header).
    pub provider: String,
    pub system: String,
    pub entries: u64,
}

/// A file the pipeline could not process.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct IngestErrorItem {
    /// The client's original name for the file.
    pub path: String,
    pub error: String,
}

/// An archive member the pipeline refused (zip64, encrypted,
/// unsupported method, central-directory lies, …).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct IngestMemberSkipItem {
    /// The client's original name for the container.
    pub path: String,
    pub member: String,
    pub reason: String,
}

// ---- GET /v1/admin/users ----

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct AdminUsersResponse {
    pub users: Vec<UserRow>,
    /// PENDING invites only: consumed ones live on as the user's
    /// provenance, expired ones are dead weight the UI need not show.
    pub invites: Vec<InviteRow>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct UserRow {
    pub username: String,
    pub role: Role,
    /// Unix seconds.
    pub created_at: i64,
    /// Granted view names (D68 ACL rows).
    pub grants: Vec<String>,
    /// Live (unexpired) session count.
    pub sessions: u64,
}

/// A pending invite. Only `blake3(token)` is stored — the token itself
/// appeared exactly once, in the mint response's fragment URL.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct InviteRow {
    /// blake3 of the token string, lowercase hex — the revocation key.
    pub token_hash: String,
    pub role: Role,
    /// Unix seconds.
    pub expires_at: i64,
    /// Minting username; null for loopback/CLI mints (no user row).
    pub created_by: Nullable<String>,
}

// ---- POST /v1/admin/invites ----

/// Invite mint parameters. An unknown `role` variant is the
/// extractor's typed 400 (`ApiJson`), so the field is a real [`Role`].
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct InviteMintRequest {
    /// Defaults to `friend`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub role: Option<Role>,
    /// 1-365; defaults to 7 (D68) — an effectively-eternal invite is a
    /// standing credential, which is what invites exist to avoid.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_days: Option<i64>,
}

/// The mint answer: a fragment URL (`/invite#<token>`) so the token
/// never appears in server logs or Referer headers.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct InviteMintResponse {
    pub url_path: String,
    /// Unix seconds.
    pub expires_at: i64,
}

// ---- POST /v1/admin/grants ----

/// Grant a friend a view (D68).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct GrantAddRequest {
    pub username: String,
    pub view: String,
}

// ---- DELETE /v1/admin/sessions/{username} ----

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct SessionsRevokedResponse {
    /// Sessions deleted.
    pub revoked: u64,
}

// ---- spec emission ----

/// The /v1 contract as an OpenAPI 3.1 document (operations live in
/// [`paths`]; utoipa collects referenced schemas transitively).
#[must_use]
pub fn openapi() -> utoipa::openapi::OpenApi {
    paths::openapi()
}

/// The spec as STABLE JSON: round-tripped through `serde_json::Value`
/// (BTreeMap-backed maps ⇒ keys sort), pretty-printed, trailing
/// newline. Byte-for-byte reproducible — the staleness test and the
/// checked-in `openapi.json` both depend on exactly this rendering.
#[must_use]
pub fn openapi_json() -> String {
    let value = serde_json::to_value(openapi()).expect("spec serializes");
    let mut out = serde_json::to_string_pretty(&value).expect("spec serializes");
    out.push('\n');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The checked-in spec IS the contract artifact (D69): a stale
    /// copy means the types moved without the spec (and the TS client
    /// generated from it) moving too — red suite, not a hand step.
    #[test]
    fn checked_in_spec_is_current() {
        let checked_in = include_str!("../openapi.json");
        let generated = openapi_json();
        assert!(
            checked_in == generated,
            "crates/datboi-api/openapi.json is stale: \
             run `cargo run -p datboi-api --bin datboi-gen-openapi` and commit the result"
        );
    }

    /// The spec's envelope. Path coverage is NOT asserted here — the
    /// axum route table is the other party to that agreement, so
    /// datboi-server's `v1_router_matches_the_contract` checks
    /// router↔spec set equality where the routes actually live.
    #[test]
    fn spec_declares_the_envelope() {
        let spec: serde_json::Value = serde_json::from_str(&openapi_json()).expect("parse");
        assert_eq!(spec["openapi"], "3.1.0", "OpenAPI 3.1 (D69)");
        // Both credential presentations are declared (D68).
        let schemes = spec["components"]["securitySchemes"]
            .as_object()
            .expect("securitySchemes");
        assert!(schemes.contains_key("session_cookie"));
        assert!(schemes.contains_key("bearer_token"));
    }

    /// The web UI switches exhaustively over these wire strings (D77)
    /// and the statuses are load-bearing for every /v1 consumer — both
    /// pinned here so neither can drift silently.
    #[test]
    fn error_codes_pin_wire_strings_and_statuses() {
        let all = [
            (ErrorCode::BadRequest, "bad_request", 400),
            (ErrorCode::UploadExpired, "upload_expired", 400),
            (ErrorCode::Unauthorized, "unauthorized", 401),
            (ErrorCode::InvalidCredentials, "invalid_credentials", 401),
            (ErrorCode::OwnerOnly, "owner_only", 403),
            (ErrorCode::InvalidInvite, "invalid_invite", 403),
            (ErrorCode::CsrfRejected, "csrf_rejected", 403),
            (ErrorCode::NotFound, "not_found", 404),
            (ErrorCode::UsernameTaken, "username_taken", 409),
            (ErrorCode::Busy, "busy", 503),
            (ErrorCode::StoreFull, "store_full", 507),
            (ErrorCode::Internal, "internal", 500),
        ];
        for (code, wire, status) in all {
            assert_eq!(
                serde_json::to_string(&code).expect("json"),
                format!("\"{wire}\""),
            );
            assert_eq!(code.http_status(), status, "{wire}");
        }
    }

    /// The omitted-vs-null distinctions the handlers rely on — each
    /// wire mode exercised once through a real contract struct, which
    /// covers every field wearing that mode's type.
    #[test]
    fn wire_shapes_match_the_handlers() {
        let whoami = WhoamiResponse {
            authenticated: false,
            username: None,
            role: None,
            via: None,
        };
        assert_eq!(
            serde_json::to_string(&whoami).expect("json"),
            r#"{"authenticated":false}"#,
            "absent identity fields are OMITTED, not null"
        );
        let unminted = ImageStatus {
            minted: false,
            hash: None,
            bytes: None,
        };
        assert_eq!(
            serde_json::to_string(&unminted).expect("json"),
            r#"{"minted":false}"#
        );
        let sizeless = ImageStatus {
            minted: true,
            hash: Some("ab".into()),
            bytes: Some(Nullable(None)),
        };
        assert_eq!(
            serde_json::to_string(&sizeless).expect("json"),
            r#"{"minted":true,"hash":"ab","bytes":null}"#,
            "minted-but-sizeless renders bytes as null, not absent"
        );
        // Detail flattening: ViewDetail serializes summary fields at
        // the top level (the wire shape view_json always had); the
        // Nullable fields stay present as explicit nulls.
        let detail = ViewDetail {
            summary: ViewSummary {
                name: "gba".into(),
                snapshot: None.into(),
                definition: None.into(),
                rows: None,
                bytes: None,
                created_at: None,
            },
            endpoints: Endpoints {
                http: "/view/gba/".into(),
                dav: "/dav/gba/".into(),
            },
            image: None.into(),
        };
        let v = serde_json::to_value(&detail).expect("json");
        assert_eq!(v["name"], "gba");
        assert_eq!(v["snapshot"], serde_json::Value::Null);
        assert_eq!(v["image"], serde_json::Value::Null);
        assert!(v.get("summary").is_none(), "flattened, not nested");
    }

    /// The old half-declared pattern (`#[schema(required = true)]` on
    /// a bare `Option` field) rendered required-but-inline-nullable
    /// properties; required nullability now rides [`Nullable`], which
    /// renders as a `$ref` to a `Nullable_*` component. Any inline
    /// null in a required property is that pattern creeping back.
    #[test]
    fn required_nullability_rides_the_wrapper() {
        let spec: serde_json::Value = serde_json::from_str(&openapi_json()).expect("parse");
        let is_inline_nullable = |prop: &serde_json::Value| {
            let type_has_null = prop["type"]
                .as_array()
                .is_some_and(|types| types.iter().any(|t| t == "null"));
            let one_of_has_null = prop["oneOf"]
                .as_array()
                .is_some_and(|items| items.iter().any(|item| item["type"] == "null"));
            type_has_null || one_of_has_null
        };
        for (name, schema) in spec["components"]["schemas"].as_object().expect("schemas") {
            let Some(required) = schema["required"].as_array() else {
                continue;
            };
            for field in required {
                let field = field.as_str().expect("field name");
                let prop = &schema["properties"][field];
                assert!(
                    !is_inline_nullable(prop),
                    "{name}.{field} is required AND inline-nullable — use wire::Nullable"
                );
            }
        }
    }

    /// JobDetail flattens the tray row to the top level; `current` is
    /// omitted between files while `finished_at` stays an explicit
    /// null until the job ends.
    #[test]
    fn job_detail_wire_shape() {
        let detail = JobDetail {
            job: Job {
                id: 3,
                name: "ingest — 2 files".into(),
                progress: 40,
                kind: JobKind::Ingest,
                state: JobRunState::Running,
                started_at: 1_000,
                finished_at: None.into(),
            },
            files_total: 2,
            files_done: 1,
            bytes_total: 100,
            bytes_done: 40,
            current: None,
            report: IngestReportBody {
                dats_imported: vec![DatImportedItem {
                    path: "dats/nds.zip".into(),
                    provider: "no-intro".into(),
                    system: "nds".into(),
                    entries: 42,
                }],
                ..IngestReportBody::default()
            },
            matched: vec![MatchedEntry {
                name: "Mario Kart DS (USA, Australia)".into(),
                source: "no-intro/nds".into(),
            }],
            matched_total: 1,
            error: None.into(),
        };
        let v = serde_json::to_value(&detail).expect("json");
        assert_eq!(v["id"], 3, "flattened, not nested under job");
        assert_eq!(v["state"], "running");
        assert_eq!(v["kind"], "ingest");
        assert!(v.get("current").is_none(), "between files: omitted");
        assert_eq!(v["finished_at"], serde_json::Value::Null);
        assert_eq!(v["error"], serde_json::Value::Null);
        assert_eq!(v["report"]["files_stored"], 0);
        // The dat lane rides the report, keyed by the client's name.
        assert_eq!(v["report"]["dats_imported"][0]["path"], "dats/nds.zip");
        assert_eq!(v["report"]["dats_imported"][0]["entries"], 42);
        assert_eq!(v["matched"][0]["source"], "no-intro/nds");
        assert_eq!(v["matched_total"], 1);
    }
}
